In [1]:
# %% [markdown]
# # HMM Backtester Validation
# Run this in Jupyter to validate `hmm_backtester.py` against your Pine HHM chart.
#
# **Workflow:**
# 1. Pick a symbol + recent date range where you have Pine signals visible
# 2. Run the backtester with verbose tracing
# 3. Compare the single-day bar-by-bar trace against Pine's labels/arrows
# 4. Check: IB range, confluence scores, entry time/price, stop, exit
#
# Drop this notebook in `C:\Users\phemm\orb_lab\` (or adjust the path below).

# %%
import sys, os
sys.path.insert(0, r'C:\Users\phemm\orb_lab\src')

import pandas as pd
import numpy as np
from datetime import datetime
from hmm_backtester import HMMBacktester, HMM_SYMBOL_PRESETS

# %% [markdown]
# ## 1. Configuration
# Pick a symbol and a SHORT date range (1-5 days) where you can eyeball Pine.

# %%
# ═══════════════════════════════════════════════════════════════
# EDIT THESE — match your Pine chart
# ═══════════════════════════════════════════════════════════════
SYMBOL       = 'AMD'
START_DATE   = '2026-02-10'   # Pick a day you have Pine labels for
END_DATE     = '2026-02-10'   # Single day = easiest to compare

# ── Confluence settings (must match Pine exactly) ──
MIN_CONF     = 3              # Pine auto-clamps to 3 when IB is off
INCLUDE_IB   = False          # Pine: "Include IB Breakout as Signal" = UNCHECKED
USE_IB_PHASE = False          # Pine: "Use IB Phase Scoring" = OFF for this validation

# ── Quality gates (match Pine toggles) ──
USE_HTF      = True           # Pine: useHTFTrendFilter
USE_VOL_FILT = True           # Pine: useVolatilityFilter
SKIP_LUNCH   = True           # Pine: avoidLunchHour

# %%
print(f"Preset for {SYMBOL}:")
preset = HMM_SYMBOL_PRESETS.get(SYMBOL, {})
for k, v in sorted(preset.items()):
    print(f"  {k:30s} = {v}")

# %% [markdown]
# ## 2. Run Backtester (verbose=True for bar-by-bar trace)

# %%
bt = HMMBacktester(
    symbol=SYMBOL,
    start_date=START_DATE,
    end_date=END_DATE,
    min_confluence=MIN_CONF,
    include_ib_in_confluence=INCLUDE_IB,
    use_ib_phase_scoring=USE_IB_PHASE,
    use_htf_trend_filter=USE_HTF,
    use_volatility_filter=USE_VOL_FILT,
    avoid_lunch_hour=SKIP_LUNCH,
    verbose=True,
)
results = bt.run()

# Print data range for sanity check
unique_dates = sorted(set(bt.df.index.date))
if unique_dates:
    print(f"\n📅 Data range: {unique_dates[0]} to {unique_dates[-1]} ({len(unique_dates)} days)")
    req_start = pd.to_datetime(START_DATE).date()
    req_end = pd.to_datetime(END_DATE).date()
    if req_start < unique_dates[0] or req_end > unique_dates[-1]:
        print(f"⚠  Requested {START_DATE} to {END_DATE} — check overlap with data range!")

# %% [markdown]
# ## 3. Trade Summary Table

# %%
if results['trades']:
    trades_df = pd.DataFrame(results['trades'])
    display(trades_df[[
        'date', 'direction', 'entry_time', 'exit_time', 'entry_price',
        'exit_price', 'exit_reason', 'stop_type', 'r_multiple',
        'confluence', 'ib_phase', 'vol_state'
    ]])
    print(f"\nTotal: {len(trades_df)} trades | "
          f"{results['total_r']:+.2f}R | "
          f"WR {results['win_rate']:.1f}% | "
          f"PF {results['profit_factor']:.2f}")
else:
    print("No trades taken. Check confluence threshold or date range.")

# %%
if results.get('skips'):
    skips_df = pd.DataFrame(results['skips'])
    print(f"\n=== SKIPPED SIGNALS ({len(skips_df)}) ===")
    display(skips_df)

# %% [markdown]
# ## 4. Single-Day Bar-by-Bar Tracer
# This is the money shot — traces every RTH bar so you can match
# against Pine's IB box, confluence table, and entry arrows.
#
# **IB columns show 0.00 when include_ib_in_confluence=False** — that's correct.
# Score = SSL + WAE + QQE + Vol only (max 4, need 3+).

# %%
def trace_day(bt, target_date: str):
    """
    Detailed bar-by-bar trace for one day.
    Prints IB build, confluence scores, quality gates, entry eval.
    Compare each line against your Pine chart bar-by-bar.
    """
    from confluence_indicators import pine_round
    
    df = bt.df
    day_df = df[df.index.date.astype(str) == target_date].copy()
    rth_df = day_df[day_df['is_rth']].copy()
    
    if len(rth_df) == 0:
        print(f"No RTH data for {target_date}")
        # Show available dates nearby
        all_dates = sorted(set(df.index.date.astype(str)))
        nearby = [d for d in all_dates if abs(pd.to_datetime(d) - pd.to_datetime(target_date)).days <= 5]
        if nearby:
            print(f"  Nearby dates with data: {', '.join(nearby[-10:])}")
        return
    
    print(f"\n{'='*90}")
    print(f"  BAR-BY-BAR TRACE: {bt.symbol} {target_date}")
    print(f"  IB Period: {bt.ib_period_minutes} min | Min Confluence: {bt.min_confluence}")
    print(f"  IB in Confluence: {bt.include_ib_in_confluence} | IB Phase Scoring: {bt.use_ib_phase_scoring}")
    print(f"  Score = SSL + WAE + QQE + Vol{' + IB' if bt.include_ib_in_confluence else ''}")
    print(f"{'='*90}\n")
    
    # Reset state for clean trace
    from hmm_backtester import IBState, VolState, Position
    ib = IBState()
    vol = VolState()
    
    ib_end_time = 9*60 + 30 + bt.ib_period_minutes
    
    if bt.include_ib_in_confluence:
        print(f"{'Time':>6}  {'O':>8} {'H':>8} {'L':>8} {'C':>8}  "
              f"{'ATR':>6} {'Vol':>5}  {'SSL':>4} {'WAE':>4} {'QQE':>4} {'VOL':>4}  "
              f"{'IB_B':>5} {'IB_S':>5}  {'Phase':>6}  Notes")
    else:
        print(f"{'Time':>6}  {'O':>8} {'H':>8} {'L':>8} {'C':>8}  "
              f"{'ATR':>6} {'Vol':>5}  {'SSL':>4} {'WAE':>4} {'QQE':>4} {'VOL':>4}  "
              f"{'Bull':>5} {'Bear':>5}  Notes")
    print("-" * 120)
    
    for i, (ts, bar) in enumerate(rth_df.iterrows()):
        time_str = ts.strftime('%H:%M')
        bar_minutes = ts.hour * 60 + ts.minute
        
        atr = bar['atr_rth']
        notes = []
        
        # ── Vol state ──
        atr_fast = bar.get('atr_fast_rth', atr)
        atr_fast_sma = bar.get('atr_fast_sma_rth', atr_fast)
        if pd.isna(atr_fast): atr_fast = atr
        if pd.isna(atr_fast_sma): atr_fast_sma = atr_fast
        
        is_orb_vol_window = 9*60+30 <= bar_minutes < 10*60
        if bar_minutes == 9*60+30:
            vol.orb_session_baseline = np.nan
        if is_orb_vol_window:
            if pd.isna(vol.orb_session_baseline):
                vol.orb_session_baseline = atr_fast_sma
            else:
                vol.orb_session_baseline = 0.9 * vol.orb_session_baseline + 0.1 * atr_fast_sma
        
        if not pd.isna(vol.orb_session_baseline) and vol.orb_session_baseline > 0:
            session_vf = atr_fast / vol.orb_session_baseline
        else:
            session_vf = 1.0
        daily_atr = bar.get('daily_atr', 1.0)
        daily_atr_slow = bar.get('daily_atr_slow', daily_atr)
        if pd.isna(daily_atr): daily_atr = 1.0
        if pd.isna(daily_atr_slow) or daily_atr_slow <= 0: daily_atr_slow = daily_atr
        htf_vf = daily_atr / daily_atr_slow if daily_atr_slow > 0 else 1.0
        vf = session_vf * htf_vf
        
        if vf < bt.low_vol_threshold:
            vs = "LOW"
        elif vf >= bt.extreme_vol_threshold:
            vs = "XTRM"
        elif vf >= bt.high_vol_threshold:
            vs = "HIGH"
        else:
            vs = "NORM"
        
        # ── IB building ──
        is_ib_window = 9*60+30 <= bar_minutes < ib_end_time
        if bar_minutes == 9*60+30:
            ib.reset_session()
            ib.ib_high = bar['high']
            ib.ib_low = bar['low']
            notes.append("IB_START")
        elif is_ib_window:
            if not pd.isna(ib.ib_high):
                ib.ib_high = max(ib.ib_high, bar['high'])
                ib.ib_low = min(ib.ib_low, bar['low'])
        
        if not is_ib_window and not ib.ib_formed and not pd.isna(ib.ib_high):
            ib.ib_formed = True
            notes.append(f"IB_FORMED H={ib.ib_high:.2f} L={ib.ib_low:.2f} R={ib.ib_high-ib.ib_low:.2f}")
        
        # ── IB phase (tracked even when not in confluence, for reference) ──
        ib_score_b = 0.0
        ib_score_s = 0.0
        phase_str = "---"
        if ib.ib_formed:
            close = bar['close']
            ib_buffer = atr * bt.ib_buffer_atr_mult if not pd.isna(atr) else 0
            ib_range = ib.ib_high - ib.ib_low
            
            if close > (ib.ib_high + ib_buffer) and not ib.ever_broke_up:
                ib.ever_broke_up = True
                notes.append("IB_BREAK_UP")
            if close < (ib.ib_low - ib_buffer) and not ib.ever_broke_down:
                ib.ever_broke_down = True
                notes.append("IB_BREAK_DN")
            
            if ib_range > 0 and ib.ever_broke_up:
                r25 = ib.ib_high - ib_range * 0.25
                r50 = ib.ib_high - ib_range * 0.50
                if bt.use_ib_phase_scoring:
                    if close > ib.ib_high:
                        ib_score_b = 1.0; phase_str = "IMP"
                    elif close >= r25:
                        ib_score_b = 1.25; phase_str = "PB25"
                    elif close >= r50:
                        ib_score_b = 0.5; phase_str = "PB50"
                    else:
                        ib_score_b = 0.0; phase_str = "FAIL"
                else:
                    # Legacy binary
                    ib_score_b = 1.0 if close > (ib.ib_high + ib_buffer) else 0.0
                    phase_str = "BRK" if ib_score_b > 0 else "---"
            
            if ib_range > 0 and ib.ever_broke_down:
                r25 = ib.ib_low + ib_range * 0.25
                r50 = ib.ib_low + ib_range * 0.50
                if bt.use_ib_phase_scoring:
                    if close < ib.ib_low:
                        ib_score_s = 1.0
                    elif close <= r25:
                        ib_score_s = 1.25
                    elif close <= r50:
                        ib_score_s = 0.5
                    else:
                        ib_score_s = 0.0
                else:
                    ib_score_s = 1.0 if close < (ib.ib_low - ib_buffer) else 0.0
        
        # ── Confluence scores ──
        full_idx = df.index.get_loc(ts)
        ssl_b = df['ssl_score_bull'].iloc[full_idx]
        ssl_s = df['ssl_score_bear'].iloc[full_idx]
        wae_b = df['wae_score_bull'].iloc[full_idx]
        wae_s = df['wae_score_bear'].iloc[full_idx]
        qqe_b = df['qqe_score_bull'].iloc[full_idx]
        qqe_s = df['qqe_score_bear'].iloc[full_idx]
        vol_sc = df['vol_score'].iloc[full_idx]
        
        # Build totals — respect IB toggle
        bull_total = ssl_b + wae_b + qqe_b + pine_round(vol_sc)
        bear_total = ssl_s + wae_s + qqe_s + pine_round(vol_sc)
        
        if bt.include_ib_in_confluence:
            bull_total += ib_score_b
            bear_total += ib_score_s
        
        # ── Quality gates ──
        htf_ema = bar.get('htf_ema', np.nan)
        htf_bull = pd.isna(htf_ema) or bar['close'] > htf_ema
        htf_bear = pd.isna(htf_ema) or bar['close'] < htf_ema
        
        atr_pct = bar.get('atr_pct', 0)
        atr_pct_avg = bar.get('atr_pct_avg', atr_pct)
        vol_ok = (not bt.use_volatility_filter or pd.isna(atr_pct_avg) or 
                  atr_pct_avg <= 0 or atr_pct >= atr_pct_avg * 0.8)
        
        is_lunch = bt.avoid_lunch_hour and (11*60+30 <= bar_minutes < 13*60+30)
        is_entry_window = (ib_end_time <= bar_minutes < 15*60+55)
        
        # ── Signal check ──
        if is_entry_window and not is_lunch and vol_ok and ib.ib_formed:
            if bull_total >= bt.min_confluence and htf_bull:
                notes.append(f"★BULL_SIG C={bull_total:.1f}")
            if bear_total >= bt.min_confluence and htf_bear:
                notes.append(f"★BEAR_SIG C={bear_total:.1f}")
        
        if is_lunch:
            notes.append("LUNCH")
        if not vol_ok:
            notes.append("VOL_SKIP")
        if is_ib_window:
            notes.append("IB_BUILD")
        
        # ── Print ──
        if bt.include_ib_in_confluence:
            print(f"{time_str:>6}  {bar['open']:>8.2f} {bar['high']:>8.2f} "
                  f"{bar['low']:>8.2f} {bar['close']:>8.2f}  "
                  f"{atr:>6.3f} {vs:>5}  "
                  f"{ssl_b:>4.0f} {wae_b:>4.0f} {qqe_b:>4.0f} {pine_round(vol_sc):>4}  "
                  f"{ib_score_b:>5.2f} {ib_score_s:>5.2f}  "
                  f"{phase_str:>6}  "
                  f"{'  '.join(notes)}")
        else:
            print(f"{time_str:>6}  {bar['open']:>8.2f} {bar['high']:>8.2f} "
                  f"{bar['low']:>8.2f} {bar['close']:>8.2f}  "
                  f"{atr:>6.3f} {vs:>5}  "
                  f"{ssl_b:>4.0f} {wae_b:>4.0f} {qqe_b:>4.0f} {pine_round(vol_sc):>4}  "
                  f"{bull_total:>5.1f} {bear_total:>5.1f}  "
                  f"{'  '.join(notes)}")
    
    # Summary
    print(f"\n{'─'*90}")
    print(f"  IB Range: {ib.ib_high:.2f} - {ib.ib_low:.2f} = {ib.ib_high - ib.ib_low:.2f}")
    print(f"  Broke Up: {ib.ever_broke_up}  Broke Down: {ib.ever_broke_down}")
    print(f"  Score formula: SSL + WAE + QQE + Vol{' + IB' if bt.include_ib_in_confluence else ''} (max {'5' if bt.include_ib_in_confluence else '4'}, need {bt.min_confluence}+)")
    print(f"{'─'*90}")

# %%
# Run the tracer on your target date
trace_day(bt, START_DATE)

# %% [markdown]
# ## 5. Pine Comparison Checklist
#
# Open your Pine HHM chart on the same symbol/date and verify:
#
# | Check | Python | Pine | Match? |
# |-------|--------|------|--------|
# | IB High | from trace | IB box top | |
# | IB Low | from trace | IB box bottom | |
# | IB Break direction | from trace | IB break label | |
# | First signal time | ★BULL/BEAR_SIG | entry arrow | |
# | Entry price | trades_df | entry label | |
# | Stop price | trades_df | stop line | |
# | Confluence score | trades_df | confluence table | |
# | Exit time/reason | trades_df | exit label | |
# | SSL/WAE/QQE per bar | trace columns | indicator panel | |
#
# **Common mismatches to watch for:**
# - IB period: Python uses `ib_period_minutes` from preset, Pine uses `ibPeriodMinutesEff`
# - HTF EMA: Python resamples 1-min→5-min, Pine uses `request.security("5",...)`
# - WAE explosion: Python computes RTH-only BB, Pine uses `request.security`
# - Lunch skip: 11:30-13:30 ET in both — verify timezone alignment

# %% [markdown]
# ## 6. Multi-Day Quick Scan
# Run a wider window and inspect the aggregate to see if trade count/direction
# roughly matches what Pine shows in Strategy Tester.

# %%
bt_wide = HMMBacktester(
    symbol=SYMBOL,
    start_date='2026-01-06',    # ← Adjust to your Pine visible range
    end_date='2026-02-10',
    min_confluence=MIN_CONF,
    include_ib_in_confluence=INCLUDE_IB,
    use_ib_phase_scoring=USE_IB_PHASE,
    use_htf_trend_filter=USE_HTF,
    use_volatility_filter=USE_VOL_FILT,
    avoid_lunch_hour=SKIP_LUNCH,
    verbose=False,
)
results_wide = bt_wide.run()

print(f"\n{'='*70}")
print(f"  MULTI-DAY SCAN: {SYMBOL}")
print(f"  {results_wide['start_date']} to {results_wide['end_date']}")
print(f"{'='*70}")
print(f"  Trades: {results_wide['total_trades']}  "
      f"W/L: {results_wide['wins']}W/{results_wide['losses']}L  "
      f"WR: {results_wide['win_rate']:.1f}%")
print(f"  Total R: {results_wide['total_r']:+.2f}  "
      f"Avg R: {results_wide['avg_r_per_trade']:+.3f}  "
      f"PF: {results_wide['profit_factor']:.2f}")

if results_wide['trades']:
    wide_df = pd.DataFrame(results_wide['trades'])
    print(f"\n  Direction split:")
    for d in ['LONG', 'SHORT']:
        sub = wide_df[wide_df['direction'] == d]
        if len(sub) > 0:
            wr = 100 * len(sub[sub['r_multiple'] > 0]) / len(sub)
            print(f"    {d:5s}: {len(sub)} trades | WR {wr:.0f}% | "
                  f"R {sub['r_multiple'].sum():+.2f}")
    
    print(f"\n  IB Phase distribution:")
    print(wide_df['ib_phase'].value_counts().to_string())
    
    print(f"\n  Exit reason distribution:")
    print(wide_df['exit_reason'].value_counts().to_string())
    
    print(f"\n  Vol state distribution:")
    print(wide_df['vol_state'].value_counts().to_string())
    
    # Per-day summary
    print(f"\n  {'Date':>12} {'Dir':>6} {'Entry':>6} {'Exit':>6} "
          f"{'R':>7} {'Conf':>5} {'IB':>5} {'Reason'}")
    print(f"  {'-'*70}")
    for _, t in wide_df.iterrows():
        print(f"  {t['date']:>12} {t['direction']:>6} {t['entry_time']:>6} "
              f"{t['exit_time']:>6} {t['r_multiple']:>+7.2f} "
              f"{t['confluence']:>5.1f} {t['ib_phase']:>5} {t['exit_reason']}")

# %% [markdown]
# ## 7. Indicator Snapshot (Debug Helper)
# If a specific bar's confluence doesn't match Pine, dump the raw indicator
# values to find which one diverges.

# %%
def indicator_snapshot(bt, target_date: str, target_time: str):
    """Dump all indicator values at a specific bar for debugging."""
    df = bt.df
    target_ts = pd.Timestamp(f"{target_date} {target_time}", tz='America/New_York')
    
    # Find closest bar
    idx = df.index.get_indexer([target_ts], method='nearest')[0]
    bar = df.iloc[idx]
    ts = df.index[idx]
    
    print(f"\n{'='*60}")
    print(f"  INDICATOR SNAPSHOT: {bt.symbol} {ts}")
    print(f"{'='*60}")
    
    print(f"\n  OHLCV:")
    print(f"    Open:   {bar['open']:.4f}")
    print(f"    High:   {bar['high']:.4f}")
    print(f"    Low:    {bar['low']:.4f}")
    print(f"    Close:  {bar['close']:.4f}")
    print(f"    Volume: {bar['volume']:.0f}")
    
    print(f"\n  ATR / VWAP / EMA:")
    print(f"    ATR (RTH):     {bar.get('atr_rth', 'N/A')}")
    print(f"    ATR (ETH):     {bar.get('atr_eth', 'N/A')}")
    print(f"    VWAP:          {bar.get('vwap', 'N/A')}")
    print(f"    EMA9:          {bar.get('ema9', 'N/A')}")
    print(f"    HTF EMA (5m):  {bar.get('htf_ema', 'N/A')}")
    
    print(f"\n  SSL Hybrid:")
    print(f"    Baseline:      {bar.get('ssl_baseline', 'N/A')}")
    print(f"    SSL Up:        {bar.get('ssl_up', 'N/A')}")
    print(f"    SSL Down:      {bar.get('ssl_down', 'N/A')}")
    print(f"    Gap bull:      {bar.get('ssl_gap_bull', 'N/A')}")
    print(f"    Gap bear:      {bar.get('ssl_gap_bear', 'N/A')}")
    print(f"    Bull confirm:  {bar.get('ssl_bull_confirm', 'N/A')}")
    print(f"    Bear confirm:  {bar.get('ssl_bear_confirm', 'N/A')}")
    print(f"    Accel bull:    {bar.get('ssl_accel_bull', 'N/A')}")
    print(f"    Accel bear:    {bar.get('ssl_accel_bear', 'N/A')}")
    print(f"    Score bull:    {bar.get('ssl_score_bull', 'N/A')}")
    print(f"    Score bear:    {bar.get('ssl_score_bear', 'N/A')}")
    
    print(f"\n  WAE:")
    print(f"    Trend up:      {bar.get('wae_trend_up', 'N/A')}")
    print(f"    Trend down:    {bar.get('wae_trend_down', 'N/A')}")
    print(f"    Explosion:     {bar.get('wae_explosion_line', 'N/A')}")
    print(f"    Bull confirm:  {bar.get('wae_bull_confirm', 'N/A')}")
    print(f"    Bear confirm:  {bar.get('wae_bear_confirm', 'N/A')}")
    print(f"    Accel bull:    {bar.get('wae_accel_bull', 'N/A')}")
    print(f"    Accel bear:    {bar.get('wae_accel_bear', 'N/A')}")
    print(f"    Score bull:    {bar.get('wae_score_bull', 'N/A')}")
    print(f"    Score bear:    {bar.get('wae_score_bear', 'N/A')}")
    
    print(f"\n  QQE:")
    print(f"    Primary RSI:   {bar.get('qqe_primary_rsi', 'N/A')}")
    print(f"    Secondary RSI: {bar.get('qqe_secondary_rsi', 'N/A')}")
    print(f"    Primary QQE:   {bar.get('qqe_primary_line', 'N/A')}")
    print(f"    BB upper:      {bar.get('qqe_bb_upper', 'N/A')}")
    print(f"    BB lower:      {bar.get('qqe_bb_lower', 'N/A')}")
    print(f"    Raw bull:      {bar.get('qqe_raw_bull', 'N/A')}")
    print(f"    Raw bear:      {bar.get('qqe_raw_bear', 'N/A')}")
    print(f"    Bull count:    {bar.get('qqe_bull_count', 'N/A')}")
    print(f"    Bear count:    {bar.get('qqe_bear_count', 'N/A')}")
    print(f"    Bull signal:   {bar.get('qqe_bull_signal', 'N/A')}")
    print(f"    Bear signal:   {bar.get('qqe_bear_signal', 'N/A')}")
    print(f"    Momentum rise: {bar.get('qqe_momentum_rising', 'N/A')}")
    print(f"    Momentum fall: {bar.get('qqe_momentum_falling', 'N/A')}")
    print(f"    Score bull:    {bar.get('qqe_score_bull', 'N/A')}")
    print(f"    Score bear:    {bar.get('qqe_score_bear', 'N/A')}")
    
    print(f"\n  Volume:")
    print(f"    Volume:        {bar.get('volume', 'N/A')}")
    print(f"    Vol Z-score:   {bar.get('vol_z', 'N/A')}")
    print(f"    Vol score:     {bar.get('vol_score', 'N/A')}")
    print(f"    Vol rounded:   {pine_round(bar.get('vol_score', 0))}")
    
    print(f"\n  Volatility:")
    print(f"    ATR %:         {bar.get('atr_pct', 'N/A')}")
    print(f"    ATR % avg:     {bar.get('atr_pct_avg', 'N/A')}")
    print(f"    Daily ATR:     {bar.get('daily_atr', 'N/A')}")
    print(f"    Daily ATR slow:{bar.get('daily_atr_slow', 'N/A')}")
    
    # Import pine_round for total calc
    from confluence_indicators import pine_round
    ssl_b = bar.get('ssl_score_bull', 0)
    wae_b = bar.get('wae_score_bull', 0)
    qqe_b = bar.get('qqe_score_bull', 0)
    vol_s = bar.get('vol_score', 0)
    ssl_s = bar.get('ssl_score_bear', 0)
    wae_s = bar.get('wae_score_bear', 0)
    qqe_s = bar.get('qqe_score_bear', 0)
    
    bull_t = ssl_b + wae_b + qqe_b + pine_round(vol_s)
    bear_t = ssl_s + wae_s + qqe_s + pine_round(vol_s)
    
    print(f"\n  ── CONFLUENCE TOTALS (IB excluded) ──")
    print(f"    Bull: SSL({ssl_b:.0f}) + WAE({wae_b:.0f}) + QQE({qqe_b:.0f}) + Vol({pine_round(vol_s)}) = {bull_t:.0f}  {'✓ PASS' if bull_t >= bt.min_confluence else '✗ FAIL'}")
    print(f"    Bear: SSL({ssl_s:.0f}) + WAE({wae_s:.0f}) + QQE({qqe_s:.0f}) + Vol({pine_round(vol_s)}) = {bear_t:.0f}  {'✓ PASS' if bear_t >= bt.min_confluence else '✗ FAIL'}")

# Example usage — change date/time to the bar you want to inspect:
# indicator_snapshot(bt, '2026-02-10', '10:35')

Preset for AMD:
  extreme_vol_threshold          = 2.0
  high_vol_threshold             = 1.3
  ib_period_minutes              = 52
  low_vol_threshold              = 0.8
  qqe_bb_length                  = 25
  qqe_rsi1_length                = 8
  qqe_rsi1_smoothing             = 5
  qqe_rsi2_length                = 4
  qqe_rsi2_smoothing             = 4
  ssl_baseline_length            = 60
  ssl_length                     = 10
  vol_lookback                   = 12
  wae_bb_length                  = 20
  wae_fast_ema                   = 14
  wae_sensitivity                = 300
  wae_slow_ema                   = 29
[HMM Presets] AMD: SSL_base=60, WAE_sens=300, QQE_rsi1=8, IB_min=52

======================================================================
  HMM BACKTESTER: AMD
  2026-02-10 to 2026-02-10
  Min Confluence: 3  IB Phase: False
======================================================================

[DataCollector] Using cache: C:\Users\phemm\orb_lab\data\cache
📊 Fetching AMD (1-min bars, 180 days, extended)...
  ✓ Loading from cache (0.3 hours old)
  Loaded 101126 1-min bars for AMD
  Resampled to 54943 2-min bars
  [*] Calculating confluence indicators (SSL, WAE, QQE, Volume)...
  [OK] Confluence indicators calculated
  Data range: 2025-08-18 to 2026-02-12 (124 days)
Processing 1 trading days...


--- 2026-02-10 ---
  [IB] Formed: H=219.39 L=214.26 Range=5.13
  [ENTRY] LONG 10:22 @ $216.21 stop=$214.88 (SWING) RR=2.05 vol=LOW conf=3.0 IB=---
  [WIN] LONG 2026-02-10 10:22->11:08: $+0.46 (+0.35R) - EMA EXIT [C:3.0 IB:---]
  [ENTRY] LONG 11:10 @ $217.31 stop=$216.55 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-02-10 11:10->11:22: $-0.76 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 13:34 @ $214.39: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 13:58 @ $215.43 stop=$214.92 (SWING) RR=2.18 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-02-10 13:58->14:18: $-0.50 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] SHORT 14:18 @ $215.00 stop=$215.41 (SWING) RR=2.26 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-02-10 14:18->14:30: $-0.41 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 14:30 @ $215.60: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:44 @ $215.06: RR 1.69 < 2.00 (SWING)
  [SKIP] SHORT 14:46 @ $214.90: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:50 @ $214.80: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:56 @ $215.31: RR 1.50 < 2.00 (SWING)
  [SKIP] SHORT 15:00 @ $214.36: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:08 @ $214.32: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:10 @ $214.08: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:12 @ $214.00: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:14 @ $213.85: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:34 @ $213.51: RR 1.64 < 2.00 (SWING)

======================================================================
  HMM BACKTEST SUMMARY: AMD
  2026-02-10 to 2026-02-10
======================================================================

  Total Trades:    4
  Total Skips:     12
  Wins/Losses/BE:  1W / 3L / 0BE
  Win Rate:        25.0%

  Total P/L:       $-1.21
  Total R:         -2.65R
  Avg R/Trade:     -0.663R

  Avg Win:         $0.46 (0.35R)
  Avg Loss:        $-0.56 (-1.00R)
  Profit Factor:   0.28
  Max Drawdown:    3.00R

======================================================================

======================================================================
TRADE DETAILS
======================================================================
2026-02-10 LONG  10:22->11:08  $216.21->$216.67  EMA EXIT           +0.35R  C:3.0 IB:---
2026-02-10 LONG  11:10->11:22  $217.31->$216.55  INITIAL STOP       -1.00R  C:3.0 IB:---
2026-02-10 LONG  13:58->14:18  $215.43->$214.92  INITIAL STOP       -1.00R  C:3.0 IB:---
2026-02-10 SHORT 14:18->14:30  $215.00->$215.41  INITIAL STOP       -1.00R  C:3.0 IB:---

Total: 4 trades, -2.65R

📅 Data range: 2025-08-18 to 2026-02-12 (124 days)

,date,direction,entry_time,exit_time,entry_price,exit_price,exit_reason,stop_type,r_multiple,confluence,ib_phase,vol_state
0,2026-02-10,LONG,10:22,11:08,216.2100,216.670000,EMA EXIT,SWING,0.346345,3.0,---,LOW
1,2026-02-10,LONG,11:10,11:22,217.3101,216.548475,INITIAL STOP,SWING,-1.000000,3.0,---,LOW
2,2026-02-10,LONG,13:58,14:18,215.4250,214.924337,INITIAL STOP,SWING,-1.000000,3.0,---,LOW
3,2026-02-10,SHORT,14:18,14:30,215.0000,215.406114,INITIAL STOP,SWING,-1.000000,3.0,---,LOW

Total: 4 trades | -2.65R | WR 25.0% | PF 0.28

=== SKIPPED SIGNALS (12) ===

,date,time,direction,entry_price,achievable_rr,min_rr,reason
0,2026-02-10,13:34,SHORT,214.390,1.500000,2.0,RR 1.50 < 2.0
1,2026-02-10,14:30,LONG,215.600,1.500000,2.0,RR 1.50 < 2.0
2,2026-02-10,14:44,SHORT,215.060,1.692167,2.0,RR 1.69 < 2.0
3,2026-02-10,14:46,SHORT,214.900,1.500000,2.0,RR 1.50 < 2.0
4,2026-02-10,14:50,SHORT,214.800,1.500000,2.0,RR 1.50 < 2.0
5,2026-02-10,14:56,LONG,215.310,1.503806,2.0,RR 1.50 < 2.0
6,2026-02-10,15:00,SHORT,214.364,1.500000,2.0,RR 1.50 < 2.0
7,2026-02-10,15:08,SHORT,214.320,1.500000,2.0,RR 1.50 < 2.0
8,2026-02-10,15:10,SHORT,214.080,1.500000,2.0,RR 1.50 < 2.0
9,2026-02-10,15:12,SHORT,214.000,1.500000,2.0,RR 1.50 < 2.0
10,2026-02-10,15:14,SHORT,213.850,1.500000,2.0,RR 1.50 < 2.0
11,2026-02-10,15:34,SHORT,213.510,1.641956,2.0,RR 1.64 < 2.0

==========================================================================================
  BAR-BY-BAR TRACE: AMD 2026-02-10
  IB Period: 52 min | Min Confluence: 3
  IB in Confluence: False | IB Phase Scoring: False
  Score = SSL + WAE + QQE + Vol
==========================================================================================

  Time         O        H        L        C     ATR   Vol   SSL  WAE  QQE  VOL   Bull  Bear  Notes
------------------------------------------------------------------------------------------------------------------------
 09:30    215.14   219.18   215.10   217.87   0.634  XTRM     1    1    0    1    3.0   1.0  IB_START  IB_BUILD
 09:32    217.85   218.72   216.45   216.97   0.751  XTRM     0    0    0    1    1.0   2.0  IB_BUILD
 09:34    217.11   219.36   216.26   219.36   0.919  XTRM     1    1    0    1    3.0   1.0  IB_BUILD
 09:36    219.35   219.39   216.67   216.81   1.047  XTRM     0    0    0    1    1.0   3.0  IB_BUILD
 09:38    216.85   217.68   216.42   216.57   1.063  XTRM     0    0    0    1    1.0   3.0  IB_BUILD
 09:40    216.48   216.94   215.41   216.56   1.096  XTRM     0    0    0    1    1.0   2.0  IB_BUILD
 09:42    216.52   216.80   215.41   216.57   1.117  XTRM     0    0    0    1    1.0   2.0  IB_BUILD
 09:44    216.64   217.05   216.06   216.34   1.108  XTRM     0    0    0    1    1.0   4.0  IB_BUILD
 09:46    216.23   216.50   215.11   215.12   1.128  XTRM     0    0    0    0    0.0   3.0  IB_BUILD
 09:48    215.12   215.60   214.26   214.72   1.143  HIGH     0    0    0    1    1.0   4.0  IB_BUILD
 09:50    214.71   216.38   214.66   216.34   1.184  HIGH     0    1    0    0    1.0   0.0  IB_BUILD
 09:52    216.28   217.00   215.98   216.87   1.172  HIGH     1    1    0    0    2.0   0.0  IB_BUILD
 09:54    216.79   216.79   216.11   216.52   1.143  HIGH     0    0    0    0    0.0   1.0  IB_BUILD
 09:56    216.61   217.08   216.01   216.74   1.138  HIGH     1    1    0    0    2.0   0.0  IB_BUILD
 09:58    216.80   216.88   215.64   215.68   1.145  NORM     0    0    0    0    0.0   2.0  IB_BUILD
 10:00    215.67   215.97   215.03   215.51   1.130  NORM     0    0    0    0    0.0   2.0  IB_BUILD
 10:02    215.53   216.10   215.25   215.54   1.111  NORM     0    0    0    0    0.0   1.0  IB_BUILD
 10:04    215.57   215.91   215.51   215.89   1.060  NORM     0    0    0    0    0.0   0.0  IB_BUILD
 10:06    215.95   216.98   215.84   216.17   1.066  NORM     0    1    0    0    1.0   0.0  IB_BUILD
 10:08    216.16   216.59   215.75   216.14   1.049  NORM     0    0    0    0    0.0   0.0  IB_BUILD
 10:10    216.16   216.65   216.09   216.26   1.014  NORM     1    1    0    0    2.0   0.0  IB_BUILD
 10:12    216.25   216.45   215.10   215.10   1.038  NORM     0    0    0    0    0.0   2.0  IB_BUILD
 10:14    215.20   215.55   214.90   215.20   1.011  NORM     0    0    0    0    0.0   0.0  IB_BUILD
 10:16    215.28   215.95   215.18   215.78   0.994  NORM     0    1    0    0    1.0   0.0  IB_BUILD
 10:18    215.79   216.19   215.50   215.99   0.972  NORM     1    1    0    0    2.0   0.0  IB_BUILD
 10:20    216.10   216.41   215.91   216.13   0.938  NORM     1    1    0    0    2.0   0.0  IB_BUILD
 10:22    216.20   216.58   216.07   216.21   0.908   LOW     1    1    1    0    3.0   0.0  IB_FORMED H=219.39 L=214.26 R=5.13  ★BULL_SIG C=3.0
 10:24    216.21   216.26   215.50   215.90   0.897   LOW     0    0    0    0    0.0   0.0
 10:26    215.94   216.40   215.62   215.70   0.889   LOW     0    0    0    0    0.0   0.0
 10:28    215.75   215.82   215.42   215.58   0.855   LOW     0    0    0    0    0.0   2.0
 10:30    215.63   216.13   215.43   215.84   0.844   LOW     1    1    0    0    2.0   0.0
 10:32    215.82   215.90   215.40   215.42   0.819   LOW     0    0    0    0    0.0   2.0
 10:34    215.48   215.62   215.33   215.53   0.781   LOW     0    0    0    0    0.0   0.0  VOL_SKIP
 10:36    215.53   215.75   215.32   215.40   0.756   LOW     0    0    0    0    0.0   2.0  VOL_SKIP
 10:38    215.41   215.61   215.20   215.24   0.731   LOW     0    0    0    0    0.0   3.0  VOL_SKIP
 10:40    215.20   215.45   215.02   215.11   0.710   LOW     0    0    0    0    0.0   3.0  VOL_SKIP
 10:42    215.16   215.99   215.11   215.94   0.722   LOW     1    1    0    1    3.0   1.0  VOL_SKIP
 10:44    215.95   216.07   215.65   215.81   0.700   LOW     0    0    0    1    1.0   1.0  VOL_SKIP
 10:46    215.82   217.18   215.82   216.85   0.748   LOW     1    1    0    1    3.0   1.0  ★BULL_SIG C=3.0
 10:48    216.87   217.08   215.77   215.84   0.788  NORM     0    0    0    1    1.0   1.0
 10:50    215.86   216.15   215.62   215.94   0.770   LOW     1    1    0    0    2.0   0.0
 10:52    215.91   216.14   215.50   216.00   0.760   LOW     1    1    0    0    2.0   0.0
 10:54    216.04   216.33   215.87   216.30   0.739   LOW     1    1    0    0    2.0   0.0
 10:56    216.25   216.31   215.87   216.30   0.718   LOW     0    0    1    0    1.0   0.0
 10:58    216.30   216.88   216.06   216.70   0.725   LOW     1    1    1    1    4.0   1.0  ★BULL_SIG C=4.0
 11:00    216.74   216.98   216.56   216.84   0.703   LOW     1    0    1    0    2.0   0.0
 11:02    216.87   217.26   216.84   217.16   0.683   LOW     1    1    1    1    4.0   1.0  ★BULL_SIG C=4.0
 11:04    217.12   217.29   217.01   217.05   0.654   LOW     0    0    1    0    1.0   0.0
 11:06    217.09   217.13   216.66   217.03   0.641   LOW     0    0    0    1    1.0   1.0
 11:08    216.98   217.19   216.57   216.67   0.640   LOW     0    0    0    1    1.0   1.0
 11:10    216.69   217.40   216.60   217.31   0.651   LOW     1    1    0    1    3.0   1.0  ★BULL_SIG C=3.0
 11:12    217.35   217.78   217.22   217.46   0.645   LOW     1    1    1    1    4.0   1.0  ★BULL_SIG C=4.0
 11:14    217.47   217.70   216.88   217.00   0.657   LOW     0    0    0    1    1.0   1.0
 11:16    216.98   217.25   216.83   217.21   0.640   LOW     1    1    0    0    2.0   0.0
 11:18    217.22   217.42   216.69   217.10   0.647   LOW     0    0    0    0    0.0   0.0
 11:20    217.10   217.37   216.56   216.56   0.658   LOW     0    0    0    0    0.0   2.0
 11:22    216.60   216.64   216.09   216.43   0.651   LOW     0    0    0    0    0.0   2.0
 11:24    216.40   216.67   216.21   216.48   0.637   LOW     0    0    0    0    0.0   1.0
 11:26    216.53   216.85   216.30   216.57   0.631   LOW     0    0    0    0    0.0   1.0
 11:28    216.55   216.85   216.50   216.82   0.611   LOW     0    0    0    0    0.0   0.0
 11:30    216.80   217.20   216.25   216.97   0.635   LOW     1    1    0    1    3.0   1.0  LUNCH
 11:32    216.97   217.14   216.63   217.00   0.626   LOW     0    0    0    0    0.0   0.0  LUNCH
 11:34    216.96   217.25   216.83   216.93   0.611   LOW     0    0    0    0    0.0   1.0  LUNCH
 11:36    216.90   216.93   216.46   216.80   0.601   LOW     0    0    0    0    0.0   2.0  LUNCH
 11:38    216.83   216.88   216.35   216.62   0.596   LOW     0    0    0    0    0.0   2.0  LUNCH
 11:40    216.67   216.74   216.07   216.38   0.601   LOW     0    0    0    0    0.0   3.0  LUNCH
 11:42    216.30   216.51   216.01   216.48   0.594   LOW     0    0    0    0    0.0   1.0  LUNCH
 11:44    216.48   216.96   216.43   216.90   0.589   LOW     0    1    0    0    1.0   0.0  LUNCH
 11:46    216.84   217.05   216.44   216.80   0.591   LOW     0    0    0    0    0.0   1.0  LUNCH
 11:48    216.81   216.88   216.03   216.71   0.609   LOW     0    0    0    0    0.0   2.0  LUNCH
 11:50    216.68   216.74   216.25   216.32   0.601   LOW     0    0    0    0    0.0   2.0  LUNCH
 11:52    216.34   216.48   216.24   216.42   0.575   LOW     0    0    0    0    0.0   1.0  LUNCH
 11:54    216.38   216.74   216.31   216.56   0.565   LOW     0    0    0    0    0.0   0.0  LUNCH
 11:56    216.56   216.87   216.47   216.57   0.553   LOW     0    0    0    0    0.0   0.0  LUNCH
 11:58    216.57   216.64   216.06   216.22   0.555   LOW     0    0    0    0    0.0   2.0  LUNCH
 12:00    216.21   216.38   216.07   216.07   0.537   LOW     0    0    0    0    0.0   3.0  LUNCH
 12:02    216.09   216.12   215.85   215.90   0.518   LOW     0    0    0    1    1.0   4.0  LUNCH
 12:04    215.91   216.10   215.81   216.04   0.501   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:06    216.10   216.10   215.70   215.86   0.494   LOW     0    0    0    0    0.0   2.0  LUNCH
 12:08    215.87   216.05   215.70   215.72   0.484   LOW     0    0    0    0    0.0   3.0  LUNCH
 12:10    215.74   215.85   215.56   215.77   0.470   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:12    215.78   215.84   215.65   215.81   0.450   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:14    215.85   215.98   215.71   215.82   0.437   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:16    215.83   216.08   215.70   216.00   0.433   LOW     0    1    0    1    2.0   1.0  LUNCH
 12:18    216.01   216.33   216.00   216.26   0.426   LOW     1    1    0    0    2.0   0.0  LUNCH
 12:20    216.25   216.26   215.55   215.79   0.446   LOW     0    0    0    1    1.0   3.0  LUNCH
 12:22    215.79   215.81   215.28   215.45   0.453   LOW     0    0    0    1    1.0   3.0  LUNCH
 12:24    215.50   215.53   215.18   215.49   0.445   LOW     0    0    0    0    0.0   1.0  LUNCH
 12:26    215.47   215.47   215.15   215.24   0.438   LOW     0    0    0    0    0.0   3.0  LUNCH
 12:28    215.24   215.54   215.21   215.41   0.430   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:30    215.42   215.50   215.25   215.41   0.417   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:32    215.41   215.53   215.30   215.47   0.404   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:34    215.45   215.54   215.26   215.26   0.395   LOW     0    0    0    0    0.0   2.0  LUNCH
 12:36    215.29   215.53   215.26   215.43   0.386   LOW     0    1    0    0    1.0   0.0  LUNCH
 12:38    215.45   215.54   215.31   215.33   0.374   LOW     0    0    0    0    0.0   1.0  LUNCH
 12:40    215.33   215.71   215.30   215.46   0.377   LOW     1    1    0    0    2.0   0.0  LUNCH
 12:42    215.44   215.47   215.16   215.46   0.372   LOW     1    1    0    0    2.0   0.0  LUNCH
 12:44    215.46   215.71   215.38   215.67   0.369   LOW     1    1    0    0    2.0   0.0  LUNCH
 12:46    215.71   215.73   215.44   215.51   0.363   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:48    215.53   215.71   215.48   215.58   0.354   LOW     1    1    0    0    2.0   0.0  LUNCH
 12:50    215.57   215.76   215.47   215.72   0.349   LOW     1    1    1    0    3.0   0.0  LUNCH
 12:52    215.75   216.18   215.63   216.15   0.363   LOW     1    1    1    1    4.0   1.0  LUNCH
 12:54    216.11   216.18   215.95   215.96   0.354   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:56    216.00   216.00   215.85   215.97   0.339   LOW     0    0    0    0    0.0   0.0  LUNCH
 12:58    215.98   216.00   215.80   215.97   0.329   LOW     0    0    0    0    0.0   0.0  LUNCH
 13:00    215.99   216.08   215.59   215.71   0.341   LOW     0    0    0    0    0.0   0.0  LUNCH
 13:02    215.71   216.00   215.51   215.67   0.351   LOW     0    0    0    1    1.0   1.0  LUNCH
 13:04    215.74   216.07   215.64   215.94   0.357   LOW     1    1    0    1    3.0   1.0  LUNCH
 13:06    215.88   215.97   215.64   215.81   0.355   LOW     0    0    0    0    0.0   0.0  LUNCH
 13:08    215.81   215.99   215.79   215.99   0.344   LOW     1    1    0    0    2.0   0.0  LUNCH
 13:10    215.99   216.09   215.88   215.98   0.334   LOW     0    0    1    0    1.0   0.0  LUNCH
 13:12    215.95   216.13   215.87   215.99   0.329   LOW     0    0    1    0    1.0   0.0  LUNCH
 13:14    215.97   216.04   215.75   215.82   0.326   LOW     0    0    0    0    0.0   0.0  LUNCH
 13:16    215.85   215.88   215.35   215.54   0.341   LOW     0    0    0    1    1.0   3.0  LUNCH
 13:18    215.54   215.75   215.30   215.65   0.348   LOW     1    0    0    1    2.0   1.0  LUNCH
 13:20    215.62   215.72   215.26   215.51   0.356   LOW     0    0    0    0    0.0   2.0  LUNCH
 13:22    215.51   215.76   215.34   215.61   0.361   LOW     0    0    0    1    1.0   2.0  LUNCH
 13:24    215.61   215.64   215.06   215.31   0.377   LOW     0    0    0    1    1.0   4.0  LUNCH
 13:26    215.33   215.38   214.62   214.67   0.404   LOW     0    0    0    1    1.0   4.0  LUNCH
 13:28    214.75   215.12   214.62   214.86   0.411   LOW     0    0    0    1    1.0   2.0  LUNCH
 13:30    214.83   215.14   214.65   214.92   0.417   LOW     0    0    0    1    1.0   1.0
 13:32    214.90   215.10   214.74   214.81   0.413   LOW     0    0    0    0    0.0   2.0
 13:34    214.86   214.93   214.13   214.39   0.440   LOW     0    0    0    1    1.0   4.0  ★BEAR_SIG C=4.0
 13:36    214.39   215.09   214.28   214.99   0.467   LOW     0    0    0    1    1.0   1.0
 13:38    215.03   215.20   214.97   215.05   0.450   LOW     0    1    0    0    1.0   0.0
 13:40    215.11   215.29   215.05   215.09   0.435   LOW     0    1    0    0    1.0   0.0
 13:42    215.09   215.21   215.00   215.12   0.419   LOW     0    1    0    0    1.0   0.0
 13:44    215.11   215.20   214.98   215.03   0.405   LOW     0    0    0    0    0.0   1.0
 13:46    215.04   215.07   214.71   214.96   0.402   LOW     0    0    0    0    0.0   1.0
 13:48    214.97   215.15   214.94   215.10   0.388   LOW     0    1    0    0    1.0   0.0
 13:50    215.13   215.33   215.07   215.18   0.379   LOW     1    1    0    0    2.0   0.0
 13:52    215.15   215.20   214.99   215.20   0.367   LOW     1    0    0    0    1.0   0.0
 13:54    215.13   215.19   214.93   215.03   0.360   LOW     0    0    0    0    0.0   0.0
 13:56    215.10   215.54   215.08   215.33   0.371   LOW     1    1    0    0    2.0   0.0
 13:58    215.31   215.56   215.30   215.43   0.363   LOW     1    1    1    0    3.0   0.0  ★BULL_SIG C=3.0
 14:00    215.39   215.58   215.18   215.57   0.366   LOW     1    1    1    0    3.0   0.0  ★BULL_SIG C=3.0
 14:02    215.57   215.57   215.33   215.47   0.357   LOW     0    0    1    0    1.0   0.0
 14:04    215.50   215.54   215.25   215.35   0.352   LOW     0    0    0    0    0.0   0.0
 14:06    215.28   215.35   215.17   215.22   0.340   LOW     0    0    0    0    0.0   0.0
 14:08    215.20   215.40   215.11   215.20   0.336   LOW     0    0    0    0    0.0   0.0
 14:10    215.18   215.24   214.97   215.09   0.332   LOW     0    0    0    0    0.0   1.0
 14:12    215.02   215.25   214.98   215.22   0.327   LOW     1    0    0    0    1.0   0.0
 14:14    215.21   215.29   215.00   215.00   0.325   LOW     0    0    0    0    0.0   2.0
 14:16    215.04   215.08   214.95   215.04   0.311   LOW     1    0    0    0    1.0   0.0
 14:18    215.05   215.16   214.92   215.00   0.306   LOW     0    0    0    1    1.0   3.0  ★BEAR_SIG C=3.0
 14:20    215.00   215.32   214.97   215.26   0.309   LOW     1    1    0    1    3.0   1.0  ★BULL_SIG C=3.0
 14:22    215.33   215.33   215.04   215.16   0.307   LOW     0    0    0    0    0.0   0.0
 14:24    215.16   215.22   215.05   215.15   0.298   LOW     0    0    0    0    0.0   0.0
 14:26    215.11   215.20   215.06   215.12   0.286   LOW     0    0    0    0    0.0   0.0
 14:28    215.10   215.35   215.10   215.29   0.284   LOW     1    1    0    1    3.0   1.0  ★BULL_SIG C=3.0
 14:30    215.29   215.63   215.29   215.60   0.287   LOW     1    1    1    1    4.0   1.0  ★BULL_SIG C=4.0
 14:32    215.60   215.60   215.36   215.44   0.284   LOW     0    0    1    0    1.0   0.0
 14:34    215.44   215.48   215.20   215.39   0.284   LOW     0    0    0    1    1.0   1.0
 14:36    215.38   215.54   215.36   215.36   0.276   LOW     0    0    0    0    0.0   0.0
 14:38    215.36   215.38   215.07   215.26   0.279   LOW     0    0    0    1    1.0   2.0
 14:40    215.24   215.29   215.09   215.26   0.273   LOW     0    0    0    0    0.0   0.0
 14:42    215.30   215.40   215.06   215.12   0.278   LOW     0    0    0    0    0.0   2.0
 14:44    215.12   215.12   214.90   215.06   0.274   LOW     0    0    0    0    0.0   3.0  ★BEAR_SIG C=3.0
 14:46    215.09   215.13   214.85   214.90   0.274   LOW     0    0    0    0    0.0   3.0  ★BEAR_SIG C=3.0
 14:48    214.90   215.04   214.84   214.98   0.269   LOW     0    0    0    1    1.0   2.0
 14:50    214.99   215.04   214.75   214.80   0.271   LOW     0    0    0    0    0.0   3.0  ★BEAR_SIG C=3.0
 14:52    214.81   215.03   214.77   214.85   0.270   LOW     0    0    0    0    0.0   1.0
 14:54    214.83   214.96   214.79   214.85   0.263   LOW     0    0    0    0    0.0   0.0
 14:56    214.85   215.40   214.85   215.31   0.284   LOW     1    1    0    1    3.0   1.0  ★BULL_SIG C=3.0
 14:58    215.33   215.40   215.15   215.15   0.281   LOW     0    0    0    0    0.0   0.0
 15:00    215.13   215.13   214.15   214.36   0.333   LOW     0    0    0    1    1.0   3.0  ★BEAR_SIG C=3.0
 15:02    214.38   214.87   214.20   214.72   0.357   LOW     0    0    0    1    1.0   1.0
 15:04    214.77   214.84   214.59   214.67   0.349   LOW     0    0    0    0    0.0   2.0
 15:06    214.69   214.79   214.48   214.59   0.346   LOW     0    0    0    0    0.0   2.0
 15:08    214.60   214.67   214.16   214.32   0.358   LOW     0    0    0    1    1.0   4.0  ★BEAR_SIG C=4.0
 15:10    214.29   214.40   213.88   214.08   0.369   LOW     0    0    0    1    1.0   4.0  IB_BREAK_DN  ★BEAR_SIG C=4.0
 15:12    214.09   214.18   213.78   214.00   0.372   LOW     0    0    0    1    1.0   3.0  ★BEAR_SIG C=3.0
 15:14    213.93   214.35   213.81   213.85   0.384   LOW     0    0    0    1    1.0   4.0  ★BEAR_SIG C=4.0
 15:16    213.86   213.98   213.73   213.89   0.374   LOW     0    0    0    1    1.0   2.0
 15:18    213.90   214.40   213.71   214.30   0.397   LOW     0    1    0    1    2.0   1.0
 15:20    214.33   214.41   214.25   214.37   0.380   LOW     0    1    0    0    1.0   0.0
 15:22    214.37   214.53   214.19   214.19   0.377   LOW     0    0    0    0    0.0   1.0
 15:24    214.18   214.22   213.63   213.67   0.392   LOW     0    0    0    0    0.0   2.0
 15:26    213.67   213.81   213.57   213.61   0.381   LOW     0    0    0    0    0.0   1.0
 15:28    213.62   213.88   213.59   213.67   0.375   LOW     0    0    0    0    0.0   1.0
 15:30    213.63   214.00   213.51   213.97   0.383   LOW     0    1    0    1    2.0   1.0
 15:32    213.95   214.10   213.63   213.92   0.389   LOW     0    0    0    1    1.0   1.0
 15:34    213.95   213.95   213.51   213.51   0.393   LOW     0    0    0    1    1.0   3.0  ★BEAR_SIG C=3.0
 15:36    213.54   213.90   213.48   213.88   0.395   LOW     0    1    0    0    1.0   0.0
 15:38    213.85   214.08   213.74   213.80   0.391   LOW     0    0    0    0    0.0   1.0
 15:40    213.77   213.98   213.76   213.96   0.379   LOW     1    1    0    0    2.0   0.0
 15:42    213.95   213.98   213.67   213.76   0.374   LOW     0    0    0    0    0.0   0.0
 15:44    213.76   213.85   213.62   213.69   0.364   LOW     0    0    0    0    0.0   1.0
 15:46    213.69   213.99   213.59   213.82   0.367   LOW     1    1    0    0    2.0   0.0
 15:48    213.77   213.86   213.70   213.85   0.352   LOW     1    1    0    0    2.0   0.0
 15:50    213.77   214.00   213.54   213.79   0.360   LOW     0    0    0    1    1.0   1.0
 15:52    213.77   213.87   213.47   213.65   0.362   LOW     0    0    0    1    1.0   1.0
 15:54    213.66   213.79   213.13   213.78   0.384   LOW     1    1    0    1    3.0   1.0
 15:56    213.79   213.80   213.49   213.64   0.378   LOW     0    0    0    1    1.0   1.0
 15:58    213.62   213.80   213.51   213.60   0.372   LOW     0    0    0    1    1.0   1.0

──────────────────────────────────────────────────────────────────────────────────────────
  IB Range: 219.39 - 214.26 = 5.13
  Broke Up: False  Broke Down: True
  Score formula: SSL + WAE + QQE + Vol (max 4, need 3+)

In [1]:
bt = HMMBacktester(
    symbol='AMD',
    start_date='2026-01-10',
    end_date='2026-02-10',
    bar_size=2,
    verbose=True
)
bt.load_data()
bt.run()
results = bt.run()

NameError: name 'HMMBacktester' is not defined

In [2]:
from hmm_backtester import HMMBacktester

bt = HMMBacktester(
    symbol='AMD',
    start_date='2026-01-10',
    end_date='2026-02-10',
    bar_size=2,
    verbose=True
)
bt.load_data()
results = bt.run()

ModuleNotFoundError: No module named 'hmm_backtester'

In [3]:
import sys
sys.path.insert(0, r'C:\Users\phemm\orb_lab\src')

from hmm_backtester import HMMBacktester

bt = HMMBacktester(
    symbol='AMD',
    start_date='2026-01-10',
    end_date='2026-02-10',
    bar_size=2,
    verbose=True
)
bt.load_data()
results = bt.run()

[HMM Presets] AMD: SSL_base=60, WAE_sens=300, QQE_rsi1=8, IB_min=52
[DataCollector] Using cache: C:\Users\phemm\orb_lab\data\cache
📊 Fetching AMD (1-min bars, 180 days, extended)...
  ✓ Loading from cache (1.9 hours old)
  Loaded 101126 1-min bars for AMD
  Resampled to 54943 2-min bars
  [*] Calculating confluence indicators (SSL, WAE, QQE, Volume)...
  [OK] Confluence indicators calculated

======================================================================
  HMM BACKTESTER: AMD
  2026-01-10 to 2026-02-10
  Min Confluence: 3  IB Phase: True
======================================================================

[DataCollector] Using cache: C:\Users\phemm\orb_lab\data\cache
📊 Fetching AMD (1-min bars, 180 days, extended)...
  ✓ Loading from cache (1.9 hours old)
  Loaded 101126 1-min bars for AMD
  Resampled to 54943 2-min bars
  [*] Calculating confluence indicators (SSL, WAE, QQE, Volume)...
  [OK] Confluence indicators calculated
  Data range: 2025-08-18 to 2026-02-12 (124 days)
Processing 21 trading days...


--- 2026-01-12 ---
  [IB] Formed: H=209.17 L=199.80 Range=9.37
  [ENTRY] SHORT 10:30 @ $207.85 stop=$209.16 (SWING) RR=1.71 vol=NORMAL conf=3.0 IB=---
  [LOSS] SHORT 2026-01-12 10:30->10:46: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] LONG 11:14 @ $208.52: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 11:18 @ $207.84: RR 1.92 < 2.00 (SWING)
  [SKIP] SHORT 11:20 @ $207.35: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 13:42 @ $208.92 stop=$209.21 (SWING) RR=2.23 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-12 13:42->14:08: $+0.65 (+2.22R) - TRAILING STOP [C:3.0 IB:---]
  [SKIP] LONG 14:14 @ $208.47: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:16 @ $208.72: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:18 @ $208.75: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:24 @ $208.80: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 14:28 @ $208.79 stop=$208.63 (SWING) RR=2.50 vol=LOW conf=3.2 IB=PB25
  [WIN] LONG 2026-01-12 14:28->14:48: $+0.15 (+0.88R) - EMA EXIT [C:3.2 IB:PB25]
  [SKIP] LONG 14:58 @ $208.94: RR 1.77 < 2.00 (SWING)
  [SKIP] LONG 15:00 @ $209.05: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:08 @ $208.82 stop=$209.09 (SWING) RR=2.28 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-12 15:08->15:26: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] SHORT 15:26 @ $208.56: RR 1.77 < 2.00 (SWING)
  [SKIP] SHORT 15:34 @ $208.43: RR 1.54 < 2.00 (SWING)
  [SKIP] SHORT 15:36 @ $208.36: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:40 @ $208.32: RR 1.59 < 2.00 (SWING)
  [SKIP] LONG 15:48 @ $208.54: RR 1.51 < 2.00 (SWING)
  [ENTRY] SHORT 15:52 @ $208.38 stop=$208.62 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-12 15:52->16:00: $+0.71 (+2.91R) - END OF DAY [C:3.0 IB:---]

--- 2026-01-13 ---
  [IB] Formed: H=222.23 L=214.97 Range=7.25
  [SKIP] SHORT 10:26 @ $217.76: RR 1.54 < 2.00 (SWING)
  [SKIP] LONG 10:58 @ $219.21: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:00 @ $219.48: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 11:12 @ $219.59 stop=$218.62 (SWING) RR=2.18 vol=LOW conf=4.0 IB=---
  [LOSS] LONG 2026-01-13 11:12->11:26: $-0.98 (-1.00R) - INITIAL STOP [C:4.0 IB:---]
  [SKIP] SHORT 11:26 @ $218.56: RR 1.61 < 2.00 (VWAP)
  [ENTRY] LONG 13:30 @ $221.04 stop=$220.70 (SWING) RR=2.50 vol=LOW conf=4.2 IB=PB25
  [LOSS] LONG 2026-01-13 13:30->13:40: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.2 IB:PB25]
  [SKIP] SHORT 13:50 @ $220.10: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 14:04 @ $220.82 stop=$220.25 (SWING) RR=2.15 vol=LOW conf=4.2 IB=PB25
  [WIN] LONG 2026-01-13 14:04->14:24: $+0.82 (+1.44R) - TRAILING STOP [C:4.2 IB:PB25]
  [SKIP] LONG 14:26 @ $221.91: RR 1.75 < 2.00 (SWING)
  [ENTRY] LONG 14:30 @ $222.04 stop=$221.53 (SWING) RR=2.22 vol=LOW conf=4.2 IB=PB25
  [LOSS] LONG 2026-01-13 14:30->15:00: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.2 IB:PB25]
  [SKIP] SHORT 15:00 @ $221.82: RR 1.56 < 2.00 (SWING)
  [ENTRY] SHORT 15:10 @ $221.93 stop=$222.26 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-13 15:10->15:14: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] LONG 15:18 @ $222.35: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:20 @ $222.36: RR 1.51 < 2.00 (SWING)
  [SKIP] LONG 15:22 @ $222.47: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:26 @ $221.83: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:28 @ $221.73: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:32 @ $221.50: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:38 @ $222.81: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:48 @ $221.78: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:50 @ $221.60: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:54 @ $220.95: RR 1.50 < 2.00 (ATR)

--- 2026-01-14 ---
  [IB] Formed: H=221.68 L=215.11 Range=6.57
  [ENTRY] LONG 10:22 @ $222.25 stop=$220.38 (ATR) RR=1.50 vol=NORMAL conf=5.0 IB=IMP
  [LOSS] LONG 2026-01-14 10:22->10:28: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:5.0 IB:IMP]
  [ENTRY] LONG 10:32 @ $222.79 stop=$221.54 (SWING) RR=2.00 vol=NORMAL conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-14 10:32->10:40: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:IMP]
  [ENTRY] SHORT 10:48 @ $220.09 stop=$221.93 (ATR) RR=1.50 vol=NORMAL conf=4.0 IB=---
  [LOSS] SHORT 2026-01-14 10:48->11:22: $-1.85 (-1.00R) - INITIAL STOP [C:4.0 IB:---]
  [SKIP] LONG 11:22 @ $221.98: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:24 @ $222.07: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:26 @ $222.39: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:28 @ $223.15: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:32 @ $221.44: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:38 @ $221.29: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 13:44 @ $221.39 stop=$222.07 (SWING) RR=2.08 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-14 13:44->13:50: $-0.68 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 13:50 @ $222.25: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 13:56 @ $222.13: RR 1.68 < 2.00 (SWING)
  [SKIP] LONG 13:58 @ $222.28: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:02 @ $221.53: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:06 @ $222.09: RR 1.97 < 2.00 (SWING)
  [ENTRY] LONG 14:30 @ $221.97 stop=$221.49 (SWING) RR=2.28 vol=LOW conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-14 14:30->14:42: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:IMP]
  [ENTRY] LONG 14:46 @ $222.38 stop=$221.94 (SWING) RR=2.50 vol=LOW conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-14 14:46->14:58: $-0.44 (-1.00R) - INITIAL STOP [C:3.0 IB:IMP]
  [SKIP] SHORT 14:58 @ $220.95: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:00 @ $220.93 stop=$222.05 (ATR) RR=1.50 vol=NORMAL conf=3.0 IB=---
  [LOSS] SHORT 2026-01-14 15:00->15:02: $-1.12 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] LONG 15:02 @ $222.19 stop=$220.95 (ATR) RR=1.50 vol=NORMAL conf=4.0 IB=IMP
  [LOSS] LONG 2026-01-14 15:02->15:12: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.0 IB:IMP]
  [SKIP] SHORT 15:16 @ $221.85: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:18 @ $221.63: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:28 @ $221.38 stop=$222.13 (SWING) RR=2.26 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-14 15:28->15:32: $-0.75 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 15:32 @ $222.48: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:34 @ $222.65: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:38 @ $222.91: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:40 @ $222.90: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:50 @ $222.73 stop=$222.04 (SWING) RR=2.21 vol=LOW conf=4.0 IB=IMP
  [WIN] LONG 2026-01-14 15:50->16:00: $+0.80 (+1.16R) - END OF DAY [C:4.0 IB:IMP]

--- 2026-01-15 ---
  [IB] Formed: H=238.10 L=227.36 Range=10.74
  [SKIP] SHORT 10:28 @ $235.72: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 10:46 @ $235.82: RR 1.94 < 2.00 (SWING)
  [ENTRY] LONG 11:12 @ $237.21 stop=$236.38 (SWING) RR=2.50 vol=LOW conf=4.0 IB=---
  [LOSS] LONG 2026-01-15 11:12->11:24: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.0 IB:---]
  [SKIP] SHORT 13:38 @ $236.64: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:40 @ $236.32: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:46 @ $235.99: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 14:00 @ $235.31 stop=$235.79 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-15 14:00->14:06: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] SHORT 14:22 @ $234.37: RR 1.86 < 2.00 (SWING)
  [SKIP] SHORT 14:26 @ $233.88: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:30 @ $233.55: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:38 @ $233.24: RR 1.77 < 2.00 (SWING)
  [SKIP] SHORT 14:56 @ $232.51: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:00 @ $232.24: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:06 @ $231.82: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:14 @ $231.16: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:16 @ $231.02: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:18 @ $230.38: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:24 @ $229.49: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:30 @ $229.53: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:48 @ $228.12: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:54 @ $227.50: RR 1.50 < 2.00 (ATR)

--- 2026-01-16 ---
  [IB] Formed: H=234.45 L=228.86 Range=5.59
  [ENTRY] SHORT 10:40 @ $230.94 stop=$231.96 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-16 10:40->10:54: $-1.02 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 10:58 @ $232.96: RR 1.67 < 2.00 (VWAP)
  [SKIP] LONG 11:00 @ $233.65: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 11:18 @ $233.23 stop=$232.33 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-01-16 11:18->11:28: $-0.90 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] SHORT 13:46 @ $231.06 stop=$231.56 (SWING) RR=2.13 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-16 13:46->14:02: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] LONG 14:06 @ $231.25: RR 1.72 < 2.00 (SWING)
  [SKIP] LONG 14:08 @ $231.32: RR 1.53 < 2.00 (SWING)
  [SKIP] LONG 14:16 @ $231.64: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:20 @ $231.83: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:24 @ $231.59: RR 1.73 < 2.00 (SWING)
  [ENTRY] LONG 14:30 @ $232.32 stop=$231.94 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-01-16 14:30->14:34: $-0.39 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 15:00 @ $232.60: RR 1.62 < 2.00 (VWAP)
  [SKIP] LONG 15:08 @ $232.91: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:30 @ $231.97 stop=$232.17 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-16 15:30->15:32: $-0.20 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 15:36 @ $232.09: RR 1.79 < 2.00 (SWING)
  [ENTRY] SHORT 15:52 @ $232.13 stop=$232.48 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-16 15:52->16:00: $+0.33 (+0.98R) - END OF DAY [C:3.0 IB:---]

--- 2026-01-20 ---
  [IB] Formed: H=235.64 L=225.41 Range=10.23
  [ENTRY] LONG 10:22 @ $236.07 stop=$233.58 (ATR) RR=1.50 vol=NORMAL conf=3.0 IB=IMP
  [WIN] LONG 2026-01-20 10:22->10:46: $+1.81 (+0.73R) - EMA EXIT [C:3.0 IB:IMP]
  [ENTRY] SHORT 10:56 @ $237.53 stop=$238.63 (SWING) RR=2.40 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-20 10:56->11:00: $-1.10 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 13:30 @ $233.35: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:32 @ $232.95: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:34 @ $232.77: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:38 @ $232.36: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:48 @ $231.81: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:52 @ $231.38: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:48 @ $231.73: RR 1.55 < 2.00 (SWING)
  [SKIP] LONG 14:52 @ $231.95: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:10 @ $231.69 stop=$231.26 (SWING) RR=2.50 vol=LOW conf=3.5 IB=PB50
  [LOSS] LONG 2026-01-20 15:10->15:14: $-0.43 (-1.00R) - INITIAL STOP [C:3.5 IB:PB50]
  [SKIP] SHORT 15:14 @ $231.16: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:18 @ $231.63 stop=$231.02 (SWING) RR=2.13 vol=LOW conf=3.5 IB=PB50
  [LOSS] LONG 2026-01-20 15:18->15:38: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.5 IB:PB50]
  [ENTRY] LONG 15:44 @ $231.90 stop=$231.40 (SWING) RR=2.47 vol=LOW conf=3.5 IB=PB50
  [LOSS] LONG 2026-01-20 15:44->15:52: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.5 IB:PB50]
  [SKIP] SHORT 15:52 @ $231.75: RR 1.50 < 2.00 (ATR)

--- 2026-01-21 ---
  [IB] Formed: H=247.88 L=235.78 Range=12.10
  [ENTRY] LONG 10:32 @ $249.49 stop=$246.85 (ATR) RR=1.50 vol=NORMAL conf=4.0 IB=IMP
  [WIN] LONG 2026-01-21 10:32->10:54: $+1.12 (+0.42R) - EMA EXIT [C:4.0 IB:IMP]
  [SKIP] LONG 13:32 @ $245.74: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:44 @ $244.76: RR 1.68 < 2.00 (SWING)
  [ENTRY] LONG 13:46 @ $245.51 stop=$244.64 (SWING) RR=2.29 vol=LOW conf=3.2 IB=PB25
  [LOSS] LONG 2026-01-21 13:46->14:04: $-0.87 (-1.00R) - INITIAL STOP [C:3.2 IB:PB25]
  [SKIP] SHORT 14:04 @ $244.49: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 14:10 @ $244.72 stop=$245.43 (SWING) RR=2.46 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-21 14:10->14:24: $-0.71 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 14:24 @ $245.27: RR 1.93 < 2.00 (SWING)
  [ENTRY] LONG 14:26 @ $246.85 stop=$246.14 (VWAP) RR=2.50 vol=LOW conf=5.2 IB=PB25
  [WIN] LONG 2026-01-21 14:26->14:52: $+3.06 (+4.27R) - TRAILING STOP [C:5.2 IB:PB25]
  [SKIP] LONG 14:52 @ $250.93: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:18 @ $249.93 stop=$250.81 (SWING) RR=2.38 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-21 15:18->15:34: $+0.21 (+0.24R) - EMA EXIT [C:3.0 IB:---]
  [ENTRY] SHORT 15:50 @ $249.63 stop=$250.09 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-21 15:50->15:52: $-0.47 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] SHORT 15:54 @ $249.54 stop=$250.23 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-21 15:54->16:00: $-0.12 (-0.18R) - END OF DAY [C:3.0 IB:---]

--- 2026-01-22 ---
  [IB] Formed: H=252.00 L=246.63 Range=5.37
  [ENTRY] LONG 10:36 @ $251.51 stop=$249.84 (SWING) RR=1.86 vol=NORMAL conf=3.0 IB=---
  [LOSS] LONG 2026-01-22 10:36->10:50: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] LONG 11:08 @ $252.76: RR 1.56 < 2.00 (SWING)
  [SKIP] LONG 11:10 @ $252.93: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:12 @ $253.29: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:14 @ $253.58: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:20 @ $253.73: RR 1.65 < 2.00 (SWING)
  [ENTRY] LONG 13:34 @ $254.31 stop=$253.69 (SWING) RR=2.03 vol=LOW conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-22 13:34->13:38: $-0.62 (-1.00R) - INITIAL STOP [C:3.0 IB:IMP]
  [SKIP] SHORT 13:42 @ $253.72: RR 1.69 < 2.00 (SWING)
  [SKIP] SHORT 13:50 @ $253.30: RR 1.75 < 2.00 (SWING)
  [SKIP] SHORT 13:52 @ $253.03: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:58 @ $252.76: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:10 @ $253.38: RR 1.78 < 2.00 (SWING)
  [SKIP] LONG 14:16 @ $253.54: RR 1.50 < 2.00 (SWING)
  [SKIP] LONG 14:18 @ $253.67: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:20 @ $253.78: RR 1.55 < 2.00 (SWING)
  [SKIP] LONG 14:22 @ $253.84: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:24 @ $254.01: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:26 @ $254.64: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:28 @ $254.48: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:32 @ $254.48: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:50 @ $254.15: RR 1.56 < 2.00 (SWING)
  [SKIP] LONG 14:52 @ $254.37: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:02 @ $254.25 stop=$253.81 (SWING) RR=2.50 vol=LOW conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-22 15:02->15:06: $-0.44 (-1.00R) - INITIAL STOP [C:3.0 IB:IMP]
  [ENTRY] SHORT 15:10 @ $253.88 stop=$254.48 (SWING) RR=2.01 vol=LOW conf=4.0 IB=---
  [WIN] SHORT 2026-01-22 15:10->15:42: $+0.72 (+1.20R) - EMA EXIT [C:4.0 IB:---]
  [ENTRY] LONG 15:48 @ $253.22 stop=$252.68 (SWING) RR=2.07 vol=LOW conf=3.0 IB=IMP
  [WIN] LONG 2026-01-22 15:48->16:00: $+0.51 (+0.97R) - END OF DAY [C:3.0 IB:IMP]

--- 2026-01-23 ---
  [IB] Formed: H=266.96 L=258.06 Range=8.90
  [SKIP] SHORT 11:04 @ $261.35: RR 1.79 < 2.00 (SWING)
  [SKIP] SHORT 11:06 @ $260.85: RR 1.88 < 2.00 (SWING)
  [SKIP] SHORT 13:40 @ $257.51: RR 1.83 < 2.00 (SWING)
  [SKIP] SHORT 13:42 @ $257.09: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:44 @ $256.79: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:48 @ $256.87: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:50 @ $256.50: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:58 @ $256.49: RR 1.98 < 2.00 (SWING)
  [ENTRY] SHORT 14:04 @ $256.79 stop=$257.08 (SWING) RR=2.50 vol=LOW conf=3.0 IB=IMP
  [LOSS] SHORT 2026-01-23 14:04->14:08: $-0.29 (-1.00R) - INITIAL STOP [C:3.0 IB:IMP]
  [SKIP] LONG 14:08 @ $257.17: RR 1.81 < 2.00 (SWING)
  [SKIP] SHORT 14:12 @ $256.51: RR 1.84 < 2.00 (SWING)
  [SKIP] LONG 14:22 @ $257.24: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:24 @ $257.41: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:26 @ $257.74: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:30 @ $257.76: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:40 @ $258.27: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:42 @ $258.81: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:46 @ $258.96: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:50 @ $259.08: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:56 @ $259.44: RR 1.51 < 2.00 (SWING)
  [SKIP] LONG 14:58 @ $259.74: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:06 @ $258.84: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:08 @ $258.75: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:10 @ $258.70: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:22 @ $258.84: RR 1.66 < 2.00 (SWING)
  [SKIP] SHORT 15:24 @ $258.56: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:28 @ $258.62: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:30 @ $258.09: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:34 @ $257.98: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:38 @ $258.10: RR 1.52 < 2.00 (SWING)
  [SKIP] LONG 15:52 @ $259.17: RR 1.65 < 2.00 (SWING)
  [ENTRY] LONG 15:54 @ $259.21 stop=$258.65 (SWING) RR=2.34 vol=LOW conf=3.0 IB=---
  [WIN] LONG 2026-01-23 15:54->16:00: $+0.44 (+0.79R) - END OF DAY [C:3.0 IB:---]

--- 2026-01-26 ---
  [IB] Formed: H=258.29 L=251.86 Range=6.43
  [ENTRY] SHORT 10:24 @ $251.38 stop=$253.23 (ATR) RR=1.50 vol=NORMAL conf=4.0 IB=IMP
  [LOSS] SHORT 2026-01-26 10:24->10:44: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.0 IB:IMP]
  [ENTRY] LONG 10:44 @ $251.47 stop=$250.28 (SWING) RR=2.02 vol=LOW conf=3.0 IB=---
  [WIN] LONG 2026-01-26 10:44->11:08: $+1.26 (+1.06R) - EMA EXIT [C:3.0 IB:---]
  [SKIP] LONG 13:30 @ $253.70: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 13:32 @ $253.85: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 13:34 @ $254.00: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 13:52 @ $252.65 stop=$253.17 (VWAP) RR=2.36 vol=LOW conf=4.2 IB=PB25
  [LOSS] SHORT 2026-01-26 13:52->13:58: $-0.52 (-1.00R) - INITIAL STOP [C:4.2 IB:PB25]
  [ENTRY] SHORT 14:00 @ $252.96 stop=$253.16 (VWAP) RR=2.50 vol=LOW conf=3.2 IB=PB25
  [LOSS] SHORT 2026-01-26 14:00->14:02: $-0.21 (-1.00R) - INITIAL STOP [C:3.2 IB:PB25]
  [ENTRY] LONG 14:04 @ $253.21 stop=$252.93 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-01-26 14:04->14:12: $-0.28 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] SHORT 14:12 @ $252.91 stop=$253.16 (VWAP) RR=2.50 vol=LOW conf=3.2 IB=PB25
  [LOSS] SHORT 2026-01-26 14:12->14:26: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.2 IB:PB25]
  [ENTRY] SHORT 14:32 @ $252.75 stop=$253.01 (SWING) RR=2.50 vol=LOW conf=3.2 IB=PB25
  [LOSS] SHORT 2026-01-26 14:32->14:44: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.2 IB:PB25]
  [SKIP] SHORT 14:44 @ $252.44: RR 1.73 < 2.00 (SWING)
  [SKIP] SHORT 14:46 @ $252.02: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:52 @ $251.87: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:54 @ $251.69: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:56 @ $251.56: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:04 @ $251.28: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:08 @ $251.14: RR 1.63 < 2.00 (SWING)
  [SKIP] SHORT 15:10 @ $250.99: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:12 @ $250.82: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:20 @ $250.92: RR 1.86 < 2.00 (SWING)
  [SKIP] LONG 15:28 @ $251.56: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:44 @ $251.50 stop=$251.01 (SWING) RR=2.18 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-01-26 15:44->15:54: $-0.48 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 15:54 @ $250.96: RR 1.80 < 2.00 (SWING)

--- 2026-01-27 ---
  [IB] Formed: H=255.55 L=247.96 Range=7.59
  [ENTRY] SHORT 10:40 @ $253.44 stop=$254.08 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-27 10:40->10:44: $-0.64 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 10:48 @ $253.00: RR 1.51 < 2.00 (SWING)
  [SKIP] SHORT 10:50 @ $252.76: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 11:10 @ $253.15 stop=$253.84 (SWING) RR=2.39 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-27 11:10->11:52: $+0.91 (+1.33R) - EMA EXIT [C:3.0 IB:---]

In [4]:
# After bt.run(), dump Feb 10 confluence scores
df = bt.df
feb10 = df[df.index.date == pd.Timestamp('2026-02-10').date()]
rth = feb10[(feb10.index.hour*60 + feb10.index.minute >= 570) & 
            (feb10.index.hour*60 + feb10.index.minute < 960)]

cols = ['open','high','low','close','ssl_score_bull','ssl_score_bear',
        'wae_score_bull','wae_score_bear','qqe_score_bull','qqe_score_bear',
        'vol_score']
print(rth[cols].to_string())

NameError: name 'pd' is not defined

In [1]:
import pandas as pd

df = bt.df
feb10 = df[df.index.date == pd.Timestamp('2026-02-10').date()]
rth = feb10[(feb10.index.hour*60 + feb10.index.minute >= 570) & 
            (feb10.index.hour*60 + feb10.index.minute < 960)]

cols = ['open','high','low','close','ssl_score_bull','ssl_score_bear',
        'wae_score_bull','wae_score_bear','qqe_score_bull','qqe_score_bear',
        'vol_score']
print(rth[cols].to_string())

NameError: name 'bt' is not defined

In [2]:
import sys
sys.path.insert(0, r'C:\Users\phemm\orb_lab\src')

import importlib
import hmm_backtester, confluence_indicators
importlib.reload(confluence_indicators)
importlib.reload(hmm_backtester)
from hmm_backtester import HMMBacktester
import pandas as pd

bt = HMMBacktester(
    symbol='AMD',
    start_date='2026-01-10',
    end_date='2026-02-10',
    bar_size=2,
    verbose=True
)
bt.load_data()
results = bt.run()

[HMM Presets] AMD: SSL_base=60, WAE_sens=300, QQE_rsi1=8, IB_min=52
[DataCollector] Using cache: C:\Users\phemm\orb_lab\data\cache
📊 Fetching AMD (1-min bars, 180 days, extended)...
  ✓ Loading from cache (4.1 hours old)
  Loaded 101126 1-min bars (ETH+RTH) for AMD
  Filtered to 48002 RTH bars
  Resampled to 24002 2-min bars
  [*] Calculating confluence indicators (SSL, WAE, QQE, Volume)...
  [OK] Confluence indicators calculated

======================================================================
  HMM BACKTESTER: AMD
  2026-01-10 to 2026-02-10
  Min Confluence: 3  IB Phase: True
======================================================================

[DataCollector] Using cache: C:\Users\phemm\orb_lab\data\cache
📊 Fetching AMD (1-min bars, 180 days, extended)...
  ✓ Loading from cache (4.1 hours old)
  Loaded 101126 1-min bars (ETH+RTH) for AMD
  Filtered to 48002 RTH bars
  Resampled to 24002 2-min bars
  [*] Calculating confluence indicators (SSL, WAE, QQE, Volume)...
  [OK] Confluence indicators calculated
  Data range: 2025-08-18 to 2026-02-12 (124 days)
Processing 21 trading days...


--- 2026-01-12 ---
  [IB] Formed: H=209.17 L=199.80 Range=9.37
  [ENTRY] SHORT 10:30 @ $207.85 stop=$209.16 (SWING) RR=1.71 vol=NORMAL conf=3.0 IB=---
  [LOSS] SHORT 2026-01-12 10:30->10:46: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] LONG 11:14 @ $208.52: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 11:18 @ $207.84: RR 1.92 < 2.00 (SWING)
  [SKIP] SHORT 11:20 @ $207.35: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 13:42 @ $208.92 stop=$209.21 (SWING) RR=2.23 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-12 13:42->14:08: $+0.65 (+2.22R) - TRAILING STOP [C:3.0 IB:---]
  [SKIP] LONG 14:14 @ $208.47: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:16 @ $208.72: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:18 @ $208.75: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:24 @ $208.80: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 14:28 @ $208.79 stop=$208.63 (SWING) RR=2.50 vol=LOW conf=3.2 IB=PB25
  [WIN] LONG 2026-01-12 14:28->14:48: $+0.15 (+0.88R) - EMA EXIT [C:3.2 IB:PB25]
  [SKIP] LONG 14:58 @ $208.94: RR 1.77 < 2.00 (SWING)
  [SKIP] LONG 15:00 @ $209.05: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:08 @ $208.82 stop=$209.09 (SWING) RR=2.28 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-12 15:08->15:26: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] SHORT 15:26 @ $208.56: RR 1.77 < 2.00 (SWING)
  [SKIP] SHORT 15:34 @ $208.43: RR 1.54 < 2.00 (SWING)
  [SKIP] SHORT 15:36 @ $208.36: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:40 @ $208.32: RR 1.59 < 2.00 (SWING)
  [SKIP] LONG 15:48 @ $208.54: RR 1.51 < 2.00 (SWING)
  [ENTRY] SHORT 15:52 @ $208.38 stop=$208.62 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-12 15:52->16:00: $+0.71 (+2.91R) - END OF DAY [C:3.0 IB:---]

--- 2026-01-13 ---
  [IB] Formed: H=222.23 L=214.97 Range=7.25
  [SKIP] SHORT 10:26 @ $217.76: RR 1.54 < 2.00 (SWING)
  [SKIP] LONG 10:58 @ $219.21: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:00 @ $219.48: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:04 @ $219.45: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 11:12 @ $219.59 stop=$218.62 (SWING) RR=2.18 vol=LOW conf=4.0 IB=---
  [LOSS] LONG 2026-01-13 11:12->11:26: $-0.98 (-1.00R) - INITIAL STOP [C:4.0 IB:---]
  [SKIP] SHORT 11:26 @ $218.56: RR 1.61 < 2.00 (VWAP)
  [ENTRY] LONG 13:30 @ $221.04 stop=$220.70 (SWING) RR=2.50 vol=LOW conf=4.2 IB=PB25
  [LOSS] LONG 2026-01-13 13:30->13:40: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.2 IB:PB25]
  [SKIP] SHORT 13:50 @ $220.10: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 14:04 @ $220.82 stop=$220.25 (SWING) RR=2.15 vol=LOW conf=4.2 IB=PB25
  [WIN] LONG 2026-01-13 14:04->14:24: $+0.82 (+1.44R) - TRAILING STOP [C:4.2 IB:PB25]
  [SKIP] LONG 14:26 @ $221.91: RR 1.75 < 2.00 (SWING)
  [ENTRY] LONG 14:30 @ $222.04 stop=$221.53 (SWING) RR=2.22 vol=LOW conf=4.2 IB=PB25
  [LOSS] LONG 2026-01-13 14:30->15:00: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.2 IB:PB25]
  [SKIP] SHORT 15:00 @ $221.82: RR 1.56 < 2.00 (SWING)
  [ENTRY] SHORT 15:10 @ $221.93 stop=$222.26 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-13 15:10->15:14: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] LONG 15:18 @ $222.35: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:20 @ $222.36: RR 1.51 < 2.00 (SWING)
  [SKIP] LONG 15:22 @ $222.47: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:26 @ $221.83: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:28 @ $221.73: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:32 @ $221.50: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:38 @ $222.81: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:48 @ $221.78: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:50 @ $221.60: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:54 @ $220.95: RR 1.50 < 2.00 (ATR)

--- 2026-01-14 ---
  [IB] Formed: H=221.68 L=215.11 Range=6.57
  [ENTRY] LONG 10:22 @ $222.25 stop=$220.38 (ATR) RR=1.50 vol=NORMAL conf=5.0 IB=IMP
  [LOSS] LONG 2026-01-14 10:22->10:28: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:5.0 IB:IMP]
  [ENTRY] LONG 10:32 @ $222.79 stop=$221.54 (SWING) RR=2.00 vol=NORMAL conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-14 10:32->10:40: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:IMP]
  [ENTRY] SHORT 10:48 @ $220.09 stop=$221.93 (ATR) RR=1.50 vol=NORMAL conf=4.0 IB=---
  [LOSS] SHORT 2026-01-14 10:48->11:22: $-1.85 (-1.00R) - INITIAL STOP [C:4.0 IB:---]
  [SKIP] LONG 11:22 @ $221.98: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:24 @ $222.07: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:26 @ $222.39: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 11:28 @ $223.15: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:32 @ $221.44: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:38 @ $221.29: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 13:44 @ $221.39 stop=$222.07 (SWING) RR=2.08 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-14 13:44->13:50: $-0.68 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 13:50 @ $222.25: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 13:56 @ $222.13: RR 1.68 < 2.00 (SWING)
  [SKIP] LONG 13:58 @ $222.28: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:02 @ $221.53: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:06 @ $222.09: RR 1.97 < 2.00 (SWING)
  [ENTRY] LONG 14:30 @ $221.97 stop=$221.49 (SWING) RR=2.28 vol=LOW conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-14 14:30->14:42: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:IMP]
  [ENTRY] LONG 14:46 @ $222.38 stop=$221.94 (SWING) RR=2.50 vol=LOW conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-14 14:46->14:58: $-0.44 (-1.00R) - INITIAL STOP [C:3.0 IB:IMP]
  [SKIP] SHORT 14:58 @ $220.95: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:00 @ $220.93 stop=$222.05 (ATR) RR=1.50 vol=NORMAL conf=3.0 IB=---
  [LOSS] SHORT 2026-01-14 15:00->15:02: $-1.12 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] LONG 15:02 @ $222.19 stop=$220.95 (ATR) RR=1.50 vol=NORMAL conf=4.0 IB=IMP
  [LOSS] LONG 2026-01-14 15:02->15:12: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.0 IB:IMP]
  [SKIP] SHORT 15:16 @ $221.85: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:18 @ $221.63: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:28 @ $221.38 stop=$222.13 (SWING) RR=2.26 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-14 15:28->15:32: $-0.75 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 15:32 @ $222.48: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:34 @ $222.65: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:38 @ $222.91: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 15:40 @ $222.90: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:50 @ $222.73 stop=$222.04 (SWING) RR=2.21 vol=LOW conf=4.0 IB=IMP
  [WIN] LONG 2026-01-14 15:50->16:00: $+0.80 (+1.16R) - END OF DAY [C:4.0 IB:IMP]

--- 2026-01-15 ---
  [IB] Formed: H=238.10 L=227.36 Range=10.74
  [SKIP] SHORT 10:28 @ $235.72: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 10:46 @ $235.82: RR 1.94 < 2.00 (SWING)
  [SKIP] LONG 11:20 @ $237.91: RR 1.84 < 2.00 (SWING)
  [SKIP] SHORT 13:38 @ $236.64: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:40 @ $236.32: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:46 @ $235.99: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 14:00 @ $235.31 stop=$235.79 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-15 14:00->14:06: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] SHORT 14:22 @ $234.37: RR 1.86 < 2.00 (SWING)
  [SKIP] SHORT 14:26 @ $233.88: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:30 @ $233.55: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:38 @ $233.24: RR 1.77 < 2.00 (SWING)
  [SKIP] SHORT 14:56 @ $232.51: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:00 @ $232.24: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:06 @ $231.82: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:14 @ $231.16: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:16 @ $231.02: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:18 @ $230.38: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:24 @ $229.49: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:30 @ $229.53: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:48 @ $228.12: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:54 @ $227.50: RR 1.50 < 2.00 (ATR)

--- 2026-01-16 ---
  [IB] Formed: H=234.45 L=228.86 Range=5.59
  [ENTRY] SHORT 10:40 @ $230.94 stop=$231.96 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-16 10:40->10:54: $-1.02 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 10:58 @ $232.96: RR 1.67 < 2.00 (VWAP)
  [SKIP] LONG 11:00 @ $233.65: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 11:18 @ $233.23 stop=$232.33 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-01-16 11:18->11:28: $-0.90 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] SHORT 13:46 @ $231.06 stop=$231.56 (SWING) RR=2.13 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-16 13:46->14:02: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.0 IB:---]
  [SKIP] LONG 14:06 @ $231.25: RR 1.72 < 2.00 (SWING)
  [SKIP] LONG 14:08 @ $231.32: RR 1.53 < 2.00 (SWING)
  [SKIP] LONG 14:16 @ $231.64: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:20 @ $231.83: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:24 @ $231.59: RR 1.73 < 2.00 (SWING)
  [ENTRY] LONG 14:30 @ $232.32 stop=$231.94 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-01-16 14:30->14:34: $-0.39 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 15:00 @ $232.60: RR 1.62 < 2.00 (VWAP)
  [SKIP] LONG 15:08 @ $232.91: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:30 @ $231.97 stop=$232.17 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-16 15:30->15:32: $-0.20 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 15:36 @ $232.09: RR 1.79 < 2.00 (SWING)
  [ENTRY] SHORT 15:52 @ $232.13 stop=$232.48 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-16 15:52->16:00: $+0.33 (+0.98R) - END OF DAY [C:3.0 IB:---]

--- 2026-01-20 ---
  [IB] Formed: H=235.64 L=225.41 Range=10.23
  [ENTRY] LONG 10:22 @ $236.07 stop=$233.58 (ATR) RR=1.50 vol=NORMAL conf=5.0 IB=IMP
  [WIN] LONG 2026-01-20 10:22->10:46: $+1.81 (+0.73R) - EMA EXIT [C:5.0 IB:IMP]
  [ENTRY] SHORT 10:56 @ $237.53 stop=$238.63 (SWING) RR=2.40 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-20 10:56->11:00: $-1.10 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 13:30 @ $233.35: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:32 @ $232.95: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:34 @ $232.77: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:38 @ $232.36: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:48 @ $231.81: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:52 @ $231.38: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:48 @ $231.73: RR 1.55 < 2.00 (SWING)
  [SKIP] LONG 14:52 @ $231.95: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:10 @ $231.69 stop=$231.26 (SWING) RR=2.50 vol=LOW conf=3.5 IB=PB50
  [LOSS] LONG 2026-01-20 15:10->15:14: $-0.43 (-1.00R) - INITIAL STOP [C:3.5 IB:PB50]
  [SKIP] SHORT 15:14 @ $231.16: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:18 @ $231.63 stop=$231.02 (SWING) RR=2.13 vol=LOW conf=3.5 IB=PB50
  [LOSS] LONG 2026-01-20 15:18->15:38: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.5 IB:PB50]
  [ENTRY] LONG 15:44 @ $231.90 stop=$231.40 (SWING) RR=2.47 vol=LOW conf=3.5 IB=PB50
  [LOSS] LONG 2026-01-20 15:44->15:52: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.5 IB:PB50]
  [SKIP] SHORT 15:52 @ $231.75: RR 1.50 < 2.00 (ATR)

--- 2026-01-21 ---
  [IB] Formed: H=247.88 L=235.78 Range=12.10
  [ENTRY] LONG 10:32 @ $249.49 stop=$246.85 (ATR) RR=1.50 vol=NORMAL conf=3.0 IB=IMP
  [WIN] LONG 2026-01-21 10:32->10:54: $+1.12 (+0.42R) - EMA EXIT [C:3.0 IB:IMP]
  [SKIP] LONG 13:32 @ $245.74: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:44 @ $244.76: RR 1.68 < 2.00 (SWING)
  [ENTRY] LONG 13:46 @ $245.51 stop=$244.64 (SWING) RR=2.29 vol=LOW conf=3.2 IB=PB25
  [LOSS] LONG 2026-01-21 13:46->14:04: $-0.87 (-1.00R) - INITIAL STOP [C:3.2 IB:PB25]
  [SKIP] SHORT 14:04 @ $244.49: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 14:10 @ $244.72 stop=$245.43 (SWING) RR=2.46 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-21 14:10->14:24: $-0.71 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] LONG 14:24 @ $245.27: RR 1.93 < 2.00 (SWING)
  [ENTRY] LONG 14:26 @ $246.85 stop=$246.14 (VWAP) RR=2.50 vol=LOW conf=5.2 IB=PB25
  [WIN] LONG 2026-01-21 14:26->14:52: $+3.06 (+4.27R) - TRAILING STOP [C:5.2 IB:PB25]
  [SKIP] LONG 14:52 @ $250.93: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 15:18 @ $249.93 stop=$250.81 (SWING) RR=2.38 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-21 15:18->15:34: $+0.21 (+0.24R) - EMA EXIT [C:3.0 IB:---]
  [ENTRY] SHORT 15:50 @ $249.63 stop=$250.09 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-21 15:50->15:52: $-0.47 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] SHORT 15:54 @ $249.54 stop=$250.23 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-21 15:54->16:00: $-0.12 (-0.18R) - END OF DAY [C:3.0 IB:---]

--- 2026-01-22 ---
  [IB] Formed: H=252.00 L=246.63 Range=5.37
  [ENTRY] LONG 10:38 @ $252.68 stop=$250.55 (ATR) RR=1.50 vol=NORMAL conf=5.0 IB=IMP
  [WIN] LONG 2026-01-22 10:38->11:54: $+1.85 (+0.87R) - EMA EXIT [C:5.0 IB:IMP]
  [ENTRY] LONG 13:34 @ $254.31 stop=$253.69 (SWING) RR=2.03 vol=LOW conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-22 13:34->13:38: $-0.62 (-1.00R) - INITIAL STOP [C:3.0 IB:IMP]
  [SKIP] SHORT 13:42 @ $253.72: RR 1.69 < 2.00 (SWING)
  [SKIP] SHORT 13:50 @ $253.30: RR 1.75 < 2.00 (SWING)
  [SKIP] SHORT 13:52 @ $253.03: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:58 @ $252.76: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:10 @ $253.38: RR 1.78 < 2.00 (SWING)
  [SKIP] LONG 14:16 @ $253.54: RR 1.50 < 2.00 (SWING)
  [SKIP] LONG 14:18 @ $253.67: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:20 @ $253.78: RR 1.55 < 2.00 (SWING)
  [SKIP] LONG 14:22 @ $253.84: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:24 @ $254.01: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:26 @ $254.64: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:28 @ $254.48: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:32 @ $254.48: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:50 @ $254.15: RR 1.56 < 2.00 (SWING)
  [SKIP] LONG 14:52 @ $254.37: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:02 @ $254.25 stop=$253.81 (SWING) RR=2.50 vol=LOW conf=3.0 IB=IMP
  [LOSS] LONG 2026-01-22 15:02->15:06: $-0.44 (-1.00R) - INITIAL STOP [C:3.0 IB:IMP]
  [ENTRY] SHORT 15:10 @ $253.88 stop=$254.48 (SWING) RR=2.01 vol=LOW conf=4.0 IB=---
  [WIN] SHORT 2026-01-22 15:10->15:42: $+0.72 (+1.20R) - EMA EXIT [C:4.0 IB:---]
  [ENTRY] LONG 15:48 @ $253.22 stop=$252.68 (SWING) RR=2.07 vol=LOW conf=3.0 IB=IMP
  [WIN] LONG 2026-01-22 15:48->16:00: $+0.51 (+0.97R) - END OF DAY [C:3.0 IB:IMP]

--- 2026-01-23 ---
  [IB] Formed: H=266.96 L=258.06 Range=8.90
  [SKIP] SHORT 11:04 @ $261.35: RR 1.79 < 2.00 (SWING)
  [SKIP] SHORT 11:06 @ $260.85: RR 1.88 < 2.00 (SWING)
  [SKIP] SHORT 13:40 @ $257.51: RR 1.83 < 2.00 (SWING)
  [SKIP] SHORT 13:42 @ $257.09: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:44 @ $256.79: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:48 @ $256.87: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:50 @ $256.50: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 13:58 @ $256.49: RR 1.98 < 2.00 (SWING)
  [ENTRY] SHORT 14:04 @ $256.79 stop=$257.08 (SWING) RR=2.50 vol=LOW conf=3.0 IB=IMP
  [LOSS] SHORT 2026-01-23 14:04->14:08: $-0.29 (-1.00R) - INITIAL STOP [C:3.0 IB:IMP]
  [SKIP] LONG 14:08 @ $257.17: RR 1.81 < 2.00 (SWING)
  [SKIP] SHORT 14:12 @ $256.51: RR 1.84 < 2.00 (SWING)
  [SKIP] LONG 14:22 @ $257.24: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:24 @ $257.41: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:26 @ $257.74: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:30 @ $257.76: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:40 @ $258.27: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:42 @ $258.81: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:46 @ $258.96: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:50 @ $259.08: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:56 @ $259.44: RR 1.51 < 2.00 (SWING)
  [SKIP] LONG 14:58 @ $259.74: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:06 @ $258.84: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:08 @ $258.75: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:10 @ $258.70: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:22 @ $258.84: RR 1.66 < 2.00 (SWING)
  [SKIP] SHORT 15:24 @ $258.56: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:28 @ $258.62: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:30 @ $258.09: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:34 @ $257.98: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:38 @ $258.10: RR 1.52 < 2.00 (SWING)
  [SKIP] LONG 15:52 @ $259.17: RR 1.65 < 2.00 (SWING)
  [ENTRY] LONG 15:54 @ $259.21 stop=$258.65 (SWING) RR=2.34 vol=LOW conf=3.0 IB=---
  [WIN] LONG 2026-01-23 15:54->16:00: $+0.44 (+0.79R) - END OF DAY [C:3.0 IB:---]

--- 2026-01-26 ---
  [IB] Formed: H=258.29 L=251.86 Range=6.43
  [ENTRY] SHORT 10:24 @ $251.38 stop=$253.23 (ATR) RR=1.50 vol=NORMAL conf=4.0 IB=IMP
  [LOSS] SHORT 2026-01-26 10:24->10:44: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:4.0 IB:IMP]
  [ENTRY] LONG 10:44 @ $251.47 stop=$250.28 (SWING) RR=2.02 vol=LOW conf=3.0 IB=---
  [WIN] LONG 2026-01-26 10:44->11:08: $+1.26 (+1.06R) - EMA EXIT [C:3.0 IB:---]
  [SKIP] LONG 13:30 @ $253.70: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 13:32 @ $253.85: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 13:34 @ $254.00: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 13:52 @ $252.65 stop=$253.17 (VWAP) RR=2.36 vol=LOW conf=4.2 IB=PB25
  [LOSS] SHORT 2026-01-26 13:52->13:58: $-0.52 (-1.00R) - INITIAL STOP [C:4.2 IB:PB25]
  [ENTRY] SHORT 14:00 @ $252.96 stop=$253.16 (VWAP) RR=2.50 vol=LOW conf=3.2 IB=PB25
  [LOSS] SHORT 2026-01-26 14:00->14:02: $-0.21 (-1.00R) - INITIAL STOP [C:3.2 IB:PB25]
  [ENTRY] LONG 14:04 @ $253.21 stop=$252.93 (VWAP) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-01-26 14:04->14:12: $-0.28 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [ENTRY] SHORT 14:12 @ $252.91 stop=$253.16 (VWAP) RR=2.50 vol=LOW conf=3.2 IB=PB25
  [LOSS] SHORT 2026-01-26 14:12->14:26: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.2 IB:PB25]
  [ENTRY] SHORT 14:32 @ $252.75 stop=$253.01 (SWING) RR=2.50 vol=LOW conf=3.2 IB=PB25
  [LOSS] SHORT 2026-01-26 14:32->14:44: $+0.00 (+0.00R) - BREAK-EVEN STOP [C:3.2 IB:PB25]
  [SKIP] SHORT 14:44 @ $252.44: RR 1.73 < 2.00 (SWING)
  [SKIP] SHORT 14:46 @ $252.02: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:52 @ $251.87: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:54 @ $251.69: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 14:56 @ $251.56: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:04 @ $251.28: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:08 @ $251.14: RR 1.63 < 2.00 (SWING)
  [SKIP] SHORT 15:10 @ $250.99: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:12 @ $250.82: RR 1.50 < 2.00 (ATR)
  [SKIP] SHORT 15:20 @ $250.92: RR 1.86 < 2.00 (SWING)
  [SKIP] LONG 15:28 @ $251.56: RR 1.50 < 2.00 (ATR)
  [ENTRY] LONG 15:44 @ $251.50 stop=$251.01 (SWING) RR=2.18 vol=LOW conf=3.0 IB=---
  [LOSS] LONG 2026-01-26 15:44->15:54: $-0.48 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 15:54 @ $250.96: RR 1.80 < 2.00 (SWING)

--- 2026-01-27 ---
  [IB] Formed: H=255.55 L=247.96 Range=7.59
  [ENTRY] SHORT 10:40 @ $253.44 stop=$254.08 (SWING) RR=2.50 vol=LOW conf=3.0 IB=---
  [LOSS] SHORT 2026-01-27 10:40->10:44: $-0.64 (-1.00R) - INITIAL STOP [C:3.0 IB:---]
  [SKIP] SHORT 10:48 @ $253.00: RR 1.51 < 2.00 (SWING)
  [SKIP] SHORT 10:50 @ $252.76: RR 1.50 < 2.00 (ATR)
  [ENTRY] SHORT 11:10 @ $253.15 stop=$253.84 (SWING) RR=2.39 vol=LOW conf=3.0 IB=---
  [WIN] SHORT 2026-01-27 11:10->11:52: $+0.91 (+1.33R) - EMA EXIT [C:3.0 IB:---]
  [SKIP] SHORT 13:50 @ $250.42: RR 1.76 < 2.00 (SWING)
  [SKIP] SHORT 13:56 @ $250.24: RR 1.73 < 2.00 (SWING)
  [SKIP] SHORT 13:58 @ $250.05: RR 1.50 < 2.00 (ATR)
  [SKIP] LONG 14:08 @ $250.46: RR 1.92 < 2.00 (SWING)
  [SKIP] SHORT 14:18 @ $249.91: RR 1.50 < 2.00 (ATR)

In [4]:
df = bt.df
bar = df.loc['2026-02-10 14:18:00-05:00']
print(f"SSL bull={bar['ssl_score_bull']} bear={bar['ssl_score_bear']}")
print(f"WAE bull={bar['wae_score_bull']} bear={bar['wae_score_bear']}")
print(f"QQE bull={bar['qqe_score_bull']} bear={bar['qqe_score_bear']}")
print(f"Vol={bar['vol_score']}")
print(f"Close={bar['close']}")

SSL bull=0.0 bear=1.0
WAE bull=0.0 bear=1.0
QQE bull=0.0 bear=0.0
Vol=0.5
Close=215.0